### ISSUE TITLE
Location of Trailer data file?

### ISSUE THREAD

**Issue by geekdave** [ptsochantaris/trailer#200] opened 2015-05-11 20:12 UTC
I'd like to start clean, as I've somehow got into a state where I see trailer notifications appear, but nothing shows up in my trailer drop-down.

For example, when someone creates an issue, and @-mentions me, and assigns to me, I see the issue in notifications but there is no "My" section in the drop-down menu.

I've tried every setting I can think may be causing this but can't figure out why it's happening, so I'd just like to nuke the settings and start clean...

(of course if you have any suggestions of how to fix another way, I'm all ears!)

Thanks for the great app!

**Comment by ptsochantaris** [comment] 2015-05-11 20:46
Hi!

Yikes, that sounds quite broken - something is going very wrong indeed.

The database files for Trailer are in *~/Library/Application Support/com.housetrip.Trailer*

The preferences are in *~/Library/Preferences/com.housetrip.Trailer* (this may not exist if you've started using a recent version) and *~/Library/Group Containers/group.Trailer* (the current location of the settings)

Make sure Trailer isn't running and remove these three. You may want to keep a copy of your existing GitHub API key so you can re-enter it once you launch Trailer once again.

I hope this will help, let me know if it improves things!

**Comment by geekdave** [comment] 2015-05-11 20:57
Thanks @ptsochantaris !  I closed Trailer, removed all those files, re-launched, re-entered my API keys (both for public github, and my company's internal github enterprise) and I'm still having the same problem. :cry: 

In "Notification Center" I see a bunch of alerts for PRs and Issues, but in the drop-down menu, I see `31 PRs are hidden by your current settings` and `126 issues are hidden by your current settings`

I'm wondering if I'm missing something obvious?  What could explain this discrepancy?

**Comment by geekdave** [comment] 2015-05-11 21:35
None of the `Hide` checkboxes are checked in my repo settings.  Wondering what else would cause issues/PRs to be "hidden by your current settings" and how to reset everything to un-hidden state?

**Comment by ptsochantaris** [comment] 2015-05-11 21:59
The messages you're seeing clearly show that Trailer is moving those items away due to some criteria based on settings... Do you perhaps have "display only items with unread comments" on? Would it be possible to include here the settings plist file at the end of that Group Containers tree? (there probably isn't anything private there but please scan and redact anything you may consider private)

PS Its a bit late in my timezone so I may vanish for some hours but I'll be back :)

PPS speed tip when exploring options: you can see changes to hidden items immediately after changing an option, just open the menu while prefs are open

PPPS even faster, select the "show count of only visible items" option so you don't even need to open the drop down :)

**Comment by ptsochantaris** [comment] 2015-05-11 22:02
(Also, don't worry if none of the above works, we'll add logging that will trace the criteria if we have to, and get to the bottom of this one way or another)

**Comment by geekdave** [comment] 2015-05-11 22:17
Ok, one step closer... I really appreciate the help on this.  

I _did_ have `Only display items with unread comments` checked.  Unchecking that lets me see everything.  But I had that checked intentionally since I don't want to see things once I've "dealt with them".

The confusing thing is that with this checkbox checked, *new* issues (that specifically @-mention me, and are assigned to me) do not show up, even though I have not viewed them.

What I did to reproduce:
1. From secondary account, open an issue in a repo in my watchlist
2. @-mention and assign to my primary account
3. Refresh trailer.

Expected:
Notification center message should appear, showing new issue 
**AND** issue should appear in dropdown

Actual:
Notification center message appears.  Number of `issues hidden by your current settings` increments.  Issue does not show up in dropdown.

**Comment by ptsochantaris** [comment] 2015-05-12 14:06
Thanks for getting back to me with the setting file, but your detailed description clears up the issue quite well I think :+1:  So, it's good to know it's not a bug per-se but a behavioural issue.

Here's the thing. Your usage makes sense, but it assumes that:
- A new/assigned item will always have unread comments and
- You want existing comments badged as unread on any newly detected item unless you explicitly visit it from Trailer (meaning if you add a new repo, all new Issues and PRs will have their comments badged as unread)

What is actually happening, is that Trailer will currently mark new PRs and Issues as "read" up to the point of that item being added to your list. This is to avoid a "sea of red" when adding new repos or in high-volume situations, and it's good behaviour I think.

What you need, essentially, is this behaviour turned off, so new items' comments are always unread unless you explicitly visit them from Trailer. The trouble is, if I tweak the behaviour it will break a lot of existing usage patterns (including mine :)).

There is a middle-ground though, we can make this behaviour explicit with a (default-on) option, called "Mark item comments as read when first added". If you turn this off, new items will have their comments badged as "unread", and in combination with "show only items with unread comments" you can get to use Trailer as a "zero inbox".

(This will only work, of course, if the items you are expecting to see have comments in the first place)

Let me know your thoughts on this when you have some time.

**Comment by geekdave** [comment] 2015-05-12 14:32
Hey thanks for the detailed response! I agree with avoiding a sea of red
when a repo is newly-added.

But my main issue is that even after a repo is _already_ added and sync'd,
when a user creates an issue and @-mentions me, and/or assigns it to me, I
see the notification appear, but the issue does not show up in the drop
down. Even though I have not visited that issue in the browser. So the
issue should still be "unread" right? Assuming the initial creation and
assignment of the issue counts as an unread comment?

**Comment by ptsochantaris** [comment] 2015-05-12 14:56
No, unfortunately the creation or assignment of an issue isn't a comment in itself. The issue will just be added to your list. If in the time between that issue being created at Github, and Trailer picking it up, there are user comments on that issue, they will be assumed to be "read".

It sounds as if you may be trying to use a combination of existing options to create a behaviour that isn't possible currently. Doesn't mean that it can't be added though :)

What you seem to need is something that will hide items after you have clicked on them until they meet some criterion, like a new comment being added. Trouble, is that criterion can vary wildly from user to user, so it's not something I'd like to add as a feature unless it can be made more generic.

Also, for argument's sake, let's try another approach with existing options: Why not hide the "all" section, and activate "move assigned items to mine" and "move items mentioning me/my teams to participated"? That will give you a list of items that interest you specifically.

**Comment by ptsochantaris** [comment] 2015-11-10 14:56
Going to be closing this for now, but please feel free to re-open or create a new issue in case you think there are other ways in which we can add/tweak features to make your life easier!

**Closed by ptsochantaris** 2015-11-10 14:56 UTC
Labels: discussion
