### ISSUE TITLE
Crashes when using search filter for issues

### ISSUE THREAD

**Issue by IzumiSy** [ptsochantaris/trailer#230] opened 2015-11-26 01:00 UTC
Issue search almost always crashes when the filter of that. I have 186 issues on trailer. Is that caused by the amount of them?

**Comment by ptsochantaris** [comment] 2015-11-26 16:49
Hi @IzumiSy 

Thanks for calling this in!

First off, no, 186 issues is perfectly fine - I usually have 800+ on my list most of the time :)

Can you be more specific on what you search for? You don't have to give me specific terms, but I mean, do you for instance use a specific prefix like "repo:" or something like that? Do you use any special characters in the search string or colons (":") perhaps? Or are you just typing any characters? Which options do you have enabled in your settings for searching (i.e. in the "when filtering, always include..." section)

Also, If you can give me a crash dump from your system when Trailer blows up like that, I'll take a look at it ASAP.

If you get a chance, let me know on some of the above, hopefully we'll sort this out quickly!

**Comment by IzumiSy** [comment] 2015-11-27 16:20
Thanks for replying. After I opened this issue, I tried to find some possible reasons of this bug. Finally, I got the clue that Trailer always crashes when I try typing Japanese characters. More specifically speaking, it crashes when I try to conversion of typing characters with IME. I have never used any prefix or special characters so far. In addition, I added a pic of my filtering options FYI.

![2015-11-28 1 08 09](https://cloud.githubusercontent.com/assets/982850/11445068/86956b80-956c-11e5-80bd-69fcb5c37330.png)

**Comment by ptsochantaris** [comment] 2015-11-27 16:29
Ah, that is very useful info @IzumiSy - thanks!

From what you describe I think I've been careless with internationalisation when constructing the various queries in the code. My knowledge of Japanese is quite poor I have to admit, but I think that there is obviously some character encoding issue at work here, so I should be able to reproduce crashes by just typing random characters in.

I notice there is also a label width issue in the preferences from your screenshot above, I'll get on that too. Just to help me test, could you let me know the version of OS X that you are currently running Trailer on?

I'll go check it out now and get back to you about this issue very shortly.

**Comment by IzumiSy** [comment] 2015-11-27 16:40
I'm using Trailer with OS X Yosemite 10.10.5 on MacBook Air (Early 2015)

I would really appreciate if you resolved this bug! Trailer always helps me work on Github to catch up with lots of issues and PRs. I hope my info can help you out.

**Comment by ptsochantaris** [comment] 2015-11-27 16:44
I think it will! Thanks again for the info. We'll definitely get to the bottom of this very soon :+1:

**Comment by ptsochantaris** [comment] 2015-11-27 17:11
Hi, ok, so I've been having a look and I think I spotted quite an ugly bug that occurs when hitting "enter/return" inside the filtering field. When working in English I rarely need to do this, but I noticed that using IME it's likely that you will select an entry and press "enter" (sorry, I know this probably sounds very basic to you, but I haven't worked with IME before) Pressing enter will cause a crash in the current version due to a rather careless bug in the UI code.

I have a debug build with this particular issue fixed (and some other small enhancements I've been working on) and I was wondering if you could try testing it out to see if it will still crash as you enter Japanese characters, since it may not have been the characters themselves, but the pressing of the "enter" key as you selected them from the IME that caused the crash in the first place.

Here is the build:
https://www.dropbox.com/s/zas12a5bt4w9b57/Trailer-debug-1253.zip?dl=0

Let me know how it goes. If it still crashes, I'll keep looking, otherwise I'll put a small update out with this fix.

**Comment by IzumiSy** [comment] 2015-11-28 13:18
I checked the debug version. It seems that the crashing bug I have reported at first has been fixed :sparkles: However, it still has malfunction with Enter key.

Search filtering now starts working just after focusing off the input box. Japanese IME always uses Enter key every time to end conversion with IME typing. So I guess what should be handled is `keypress` of Enter. Languages like English dont need this procedure, so it was probably difficult to find this out.

**Comment by ptsochantaris** [comment] 2015-11-28 14:55
No, it's perfectly alright!

Please DO mention any and all issues you have with this, it's very helpful. 

So, it's good to know we're not crashing anymore, but it seems then that the input box isn't automatically triggering filtering when the text changes, if I understand correctly? If so, it sounds like it's reading the pre-Japanese text rather than the final IME output. 

I'll check this out a little later on today and create a second debug build. Sorry for all the back and forth, like you say I'm not very familiar with IME entry, so I'm missing things that may be obvious. It is however very useful knowledge for when dealing with future UI tweaks!

I'll be back a little later on with a new debug build.

**Comment by ptsochantaris** [comment] 2015-11-28 16:42
Hi, I think I may have isolated it - it seems Trailer was picking up the "enter" key press that was meant to confirm the IME entry in the search field. Let me know if this build behaves better now, of if it needs more tweaking to its behaviour:

https://www.dropbox.com/s/mhyyet76nctzee9/Trailer-debug-1256.zip?dl=0

**Comment by IzumiSy** [comment] 2015-11-29 00:50
Hi, The one last you built was completely working fine! :100: That was exactly what I expected. Nothing could be better, no need to tweaking anymore :+1: Now the bug I reported here was completely fixed. Thank you so much for a quick response and kindness until now!

**Comment by ptsochantaris** [comment] 2015-11-29 01:12
That's great news! You're very welcome, and thanks again for reporting it @IzumiSy - and please feel free to open further issues in the future if you notice any more issues related to IME input or anything else. I'm glad we could sort it out quickly.

I'll leave this issue open until the actual non-debug version is up in the next couple of days, and I'll let you know when it is so you can upgrade to it (this version should run fine for you BTW, but it's just a little less efficient on CPU and memory, plus it logs a lot of calls on the system log) I'll get that out as soon as I've wrapped up a couple of small new features I've been adding for 1.3.11 :+1:

**Comment by ptsochantaris** [comment] 2015-11-29 22:30
Hi, just wanted to let you know that the release build of 1.3.11 is up, you can update to it from "About Trailer" -> "Check For Updates"

**Comment by IzumiSy** [comment] 2015-11-30 00:48
Thank you for reminding me! I got notification of the update on this morning. Really glad to see Trailser getting better. Will enjoy work with it today :yum:

**Comment by ptsochantaris** [comment] 2015-12-01 17:04
Excellent, I hope it's going well.

I'm going to close this issue for now, but please feel free to re-open or create further issues if you spot anything else.

Thanks again for reporting this and helping improve Trailer!

**Closed by ptsochantaris** 2015-12-01 17:04 UTC
Labels: bug, in next release
