### ISSUE TITLE
Change 'All Issues' to 'All' in PR view?

### ISSUE THREAD

**Issue by mmcdaris** [ptsochantaris/trailer#300] opened 2016-11-11 23:09 UTC
I got confused because in the PR view, It says `All Issues`.

What do you think about using `All Pulls` or just `All` instead?

Here is a screenshot of what I see:

![all-issues](https://cloud.githubusercontent.com/assets/940237/20232958/c7f46d02-a820-11e6-8957-fe46c86147d8.png)

**Comment by ptsochantaris** [comment] 2016-11-12 07:37
Hi @mmcdaris, yikes, I can't believe I missed that bug. Indeed, Trailer is supposed to have a different label on PRs. I'll push out a small update in the next couple of days to fix this. Thanks for pointing it out! (Goes to show, unless there is a bug report for something, you can never be sure the developer has seen it :))

**Comment by ptsochantaris** [comment] 2016-11-21 18:05
Hi @mmcdaris, sorrry I haven't been in touch (I confess: vacations :))

I tired to reproduce your issue locally but for some reason I wasn't able to - which leads me to believe that it's a weird bug when listing items based on some sort of filtering. Do you by any chance use repo groupings in your prefs, or are you using the "default" PR/Issues grouping?

In any case, now that I'm back I'm going to make another pass at it in more detail and let you know, stay tuned.

**Comment by mmcdaris** [comment] 2016-11-21 18:14
Hi @ptsochantaris, No worries. I was using repo grouping at the time of my screenshot but have unchecked it, the issue persists without repo grouping.
Here is a screenshot of my current display preferences. Let me know if there is anything else I can fetch for you to make replicating this one easier.
<img width="894" alt="screen shot 2016-11-21 at 10 10 27" src="https://cloud.githubusercontent.com/assets/940237/20494735/310e7d78-afd3-11e6-8579-b98693024e25.png">

**Comment by ptsochantaris** [comment] 2016-11-29 10:36
Ok, I have no idea why I hadn't spotted this issue before (no pun intended :)), or even why it was actually working in some cases when I tried it out, as the code to select the correct headings for items in the menu display was *clearly* broken. Thanks for letting me know about it - it should be fixed now in this build, let me know how it goes:

https://www.dropbox.com/s/h7ubn3os6k21g5z/Trailer-titles-fix.zip?dl=0

Sorry for taking so long to get back to you about this. The fix will also be included in the upcoming 1.5.2 update soon.

**Comment by mmcdaris** [comment] 2016-11-30 23:03
Hey @ptsochantaris. No worries, thanks for the fix: 

<img width="285" alt="screen shot 2016-11-30 at 15 01 15" src="https://cloud.githubusercontent.com/assets/940237/20775050/ecab5a1a-b70d-11e6-9e51-f87fa75e78ed.png">

I'll watch out for the update. 
Thanks for making Trailer 👍, digging it!

**Comment by ptsochantaris** [comment] 2016-12-05 18:27
I'm really glad to hear that, I have fun and learn a lot while making it, so it's a win win for everyone I guess :) The 1.5.2 final is up in case you haven't seen it, feel free to update to it (auto-update should do the job from the current build) whenever you like.

Will close this for now. Thanks again for spotting and reporting this, and feel free to keep opening issues and reporting any problems you may spot in the future!

**Closed by ptsochantaris** 2016-12-05 18:27 UTC
Labels: bug
