### ISSUE TITLE
Trailer is unresponsive most of the time

### ISSUE THREAD

**Issue by yihongang** [ptsochantaris/trailer#420] opened 2020-11-11 08:38 UTC
Console logs seems to hint that it's due to updating PullRequest status item. Each time this happens it takes more than a minute before it responds again (after saving DB) . I get a spinning beach ball in the mean time (mac OS). Is there anything specific in the logs that would help debug this?

```
default	16:30:09.830308 +0800	Trailer	Updating PullRequest status item
default	16:30:51.583983 +0800	Trailer	TIC TCP Conn Cancel [1215:0x60001d5bb300]
....
....
default	16:31:20.733695 +0800	Trailer	Saving DB
```

**Comment by ptsochantaris** [comment] 2020-11-14 17:48
Hi @yihongang and thanks for reporting this. Statuses are indeed a bit hard to digest by Trailer because of the way GitHub serves them, but I can't quite imagine they would be so heavy that it would take a whole minute to process, especially on the main thread. Just to give an indication of the load involved here, can you describe a bit more the kind of settings you have? For instance, are you viewing statuses for all items, how many items with visible statuses are visible, does the problem vanish if you turn off the option to display statuses? And any other info which you think may be helpful in suggesting what may be going on there.

**Comment by yihongang** [comment] 2020-11-18 06:01
Statuses as in this? 
![image](https://user-images.githubusercontent.com/12490533/99491249-5c9c7700-29a6-11eb-8682-1edb3bca82b9.png)

It looks disabled.

But I do see this, is that a reason?
![image](https://user-images.githubusercontent.com/12490533/99491299-73db6480-29a6-11eb-969b-d1252108e82c.png)

**Comment by ptsochantaris** [comment] 2020-11-29 12:16
Hi @yihongang and thanks for the update, will dig into it. I've noticed there is some huge delay that occurs when trying to edit group labels on the repository tabs as well in Big Sur for some reason as well, with no code changes on my end. Just out of curiosity, which macOS version are you running?

**Comment by ptsochantaris** [comment] 2020-11-29 17:18
I've created a test build with the fix for the issue I mentioned just above, and since the class affected touches other parts of the UI, there's a remote chance it could perhaps affect your issue, so I'm attaching it here in case you find some time to give it a go and see if anything improves. My gut feeling is that it probably won't, I'm afraid to admit, but just in case :)

[Trailer-1573.zip](https://github.com/ptsochantaris/trailer/files/5612524/Trailer-1573.zip)

That aside, it may help quite a bit if you can try disabling various repos to see if the issue can be localised to a specific repo or repos - I would probably bet that the problem isn't just a processing delay but some bug that's triggered by a specific corner case in some PR or Issue, and if we manage to locate that we'll be more than half way there. Sorry for the slow pace in tracking this issue, I'm really hoping to manage to reproduce it somehow on my end as well.

**Comment by yihongang** [comment] 2020-12-01 11:09
I'm running Mojave. The test build still has the issue for me. 

Not sure if it is relevant, I do have quite a few snoozed PRs. I haven't had the time to try disabling repos to isolate where/what it's happening for, sorry.

**Comment by ptsochantaris** [comment] 2020-12-01 16:51
Thanks for the update - will check on a Mojave VM just in case as well. Will also try with some snoozed PRs as well. When you do have some time to try out removing some repos, please do have a go and let me know. It would, for example, be super-useful to know that this occurs with e.g. 10 PRs on a list from open-source repos, at which point you could export your config so I can replicate on a local VM.

**Comment by yihongang** [comment] 2021-02-02 09:24
Minor update on memory consumption behavior, when the number of PRs in the `Mine` section reduced from 20+ to 7, I also noticed that the memory-use drop from 4-5gb to around 2gb. Not sure if it's a causal relationship, as something else might have also changed in the 3 months

**Comment by cfstras** [comment] 2021-03-30 08:49
> Hi @yihongang and thanks for the update, will dig into it. I've noticed there is some huge delay that occurs when trying to edit group labels on the repository tabs as well in Big Sur for some reason as well, with no code changes on my end. Just out of curiosity, which macOS version are you running?

Can confirm this, changing group makes the app unresponsive for about a minute. Version 1.7.4 (1572), Big Sur 11.2.3 (M1)

**Comment by ptsochantaris** [comment] 2023-07-01 16:49
The new update is now out and should correct this issue. Going to close it for now, but as always please feel free to re-open if there's more to do, or create new issues!

**Closed by ptsochantaris** 2023-07-01 16:49 UTC
Labels: awaiting feedback
