### ISSUE TITLE
Filter out archived repos

### ISSUE THREAD

**Issue by Kageetai** [ptsochantaris/trailer#475] opened 2023-06-26 10:06 UTC
Currently, trailer also shows PRs from archived repositories, which can't be closed or hidden or anything anymore.
The default query GitHub uses on https://github.com/pulls is `is:open is:pr author:[USER] archived:false`. Maybe trailer can add the archived filter as well?!

**Comment by ptsochantaris** [comment] 2023-06-26 10:09
Hi @Kageetai!

You'll be happy to know that Trailer has an option to do this - you can enable it in Preferences -> Repositories -> Advanced, and it's the third option like in the screenshot below:

<img width="615" alt="Screenshot 2023-06-26 at 11 08 38" src="https://github.com/ptsochantaris/trailer/assets/521581/5545cbed-224b-45e1-b10b-66774f77b62c">

**Comment by Kageetai** [comment] 2023-06-26 10:18
True, I overlooked that option. The repository is greyed out on the last actually, but the PR is still shown in trailer itself.

**Comment by ptsochantaris** [comment] 2023-06-26 10:23
Can you try a re-scan of the repos followed by a refresh? I suspect it's just a matter of the listing being out of sync. In theory Trailer should have automatically marked that repo "Hidden" for you with this option on, after you re-sync the repos - if it isn't marked as hidden something may be going wrong in Trailer :) Let me know how you get on.

**Comment by Kageetai** [comment] 2023-06-26 10:31
Oh, it wasn't that, but just noticed that even though the repo was greyed out and hidden in the list, the "Pull Request" dropdown was set to "authored" for some reason. That's not even an option I can select myself there...
Changed that now and the PR disappeared. Thanks for the support

**Comment by Kageetai** [comment] 2023-06-26 10:34
Hmm actually it constantly returns to "authored" as soon as I close the preferences window..

**Comment by ptsochantaris** [comment] 2023-06-26 11:50
Ah that's interesting - "Authored" is when it's including an authored PR or Issue from that repo, so the issue probably is that it's showing the authored item, even though you asked it to hide archived repos. If you disable the "show authored items from any repo" option, does it go away?

**Comment by Kageetai** [comment] 2023-06-26 13:07
Yes, it goes away then. But also some other PRs, that would like to keep :D

**Comment by ptsochantaris** [comment] 2023-06-26 13:54
Cool, so at least we know what's going on. So the issue is that you're asked Trailer to both show your authored open items, and hide archived repos. To me it _sounds_ like it's doing the right thing, as in, showing you your open item since you authored it, even though it comes from a repo which is archived - i.e. it's choosing to show more instead of less. But I'm definitely open to your thoughts and suggestions on how this could be improved. Or please do feel free to correct me if I've misunderstood and e.g. the item you're talking about was closed for example.

**Comment by ptsochantaris** [comment] 2023-06-30 08:35
I think I found a tweak that should fix this issue - could you give this test build a go and let me know if it improves things for you?

[Trailer.app-test.zip](https://github.com/ptsochantaris/trailer/files/11914582/Trailer.app-test.zip)

**Comment by ptsochantaris** [comment] 2023-06-30 09:06
Oh brilliant, I'll be sure to add this to the upcoming release then 👍 Thanks for testing!

**Comment by ptsochantaris** [comment] 2023-07-01 16:46
The new update is now out and should correct this issue. Going to close it for now, but as always please feel free to re-open if there's more to do, or create new issues!

**Closed by ptsochantaris** 2023-07-01 16:46 UTC
