### ISSUE TITLE
I never see my team mentions

### ISSUE THREAD

**Issue by BMorearty** [ptsochantaris/trailer#277] opened 2016-06-19 03:10 UTC
I use GitHub Enterprise. Whenever someone mentions my team, I don't see it in Trailer.

It's very common for people on my team to mention the team in the PR description, not in a comment. The format is usually:

```
Cc: @org/team-name
```

As in this example, my team name has a hyphen in it. Could this be why I don't see anything in Trailer?

In prefs, I have checked the box to move an item to "Mentioned" if my team is mentioned.

(What I would actually like is to see team mentions in a separate section, not mixed in with personal mentions, because my team gets a ton of mentions.)

**Comment by ptsochantaris** [comment] 2016-06-20 07:48
Hi and thanks for opening this separate issue.

So, I've dug around a bit to see if I can replicate the issue, and I can. However, it seems to happen under a specific circumstance: if the Cc is added after the issue is created and synced down to Trailer. The reason for this is that GitHub won't mark the item as modified if you edit its body. For some reason it will only mark the item modified when comments are added or deleted.

This means that Trailer never "sees" the new body with the cc in it, and hence doesn't take it into account (after the first sync of the item). If the cc is there from the start, it seems to work fine (including the case where the team name includes hyphens.)

As soon as I added a comment to the test issue I had created, the item updated itself on the Trailer list and moved to "mentioned".

So, in short, this may not be a case of fixing a small logic bug, but related to the wider sync logic. That said, I was about to start working of just that :) - the idea being that Trailer will no longer rely on the updated_at values of items, or rather, supplement them by scanning the event stream as well and marking items "dirty" per-item and not just per-repo.

So, the good news is that I think this will go away once Trailer syncs that way, and this is coming soon. The bad news is that it's not a simple change, so it may take a little more time than you may have expected to correct this. If you're interested, I'd be more than happy to keep you up to date with the new sync-logic builds, so you can both get your fixed behavior faster, and also help test the new syncing logic :)

Hope this makes some sense. I should have more news for you soon.

**Comment by ptsochantaris** [comment] 2021-07-03 17:23
Hi, I'm dusting off the old queue of issues, and I'll be closing this one for now since v4 API sync will in fact detect and sync down PRs when their body is edited, but please feel free to open another issue if you feel there's more that can be done on this in the future.

**Closed by ptsochantaris** 2021-07-03 17:23 UTC
Labels: API limitation, bug
