### ISSUE TITLE
Separate "me" and "team" assignments when moving items

### ISSUE THREAD

**Issue by Nezteb** [ptsochantaris/trailer#448] opened 2021-10-19 04:07 UTC
In the "Reviews" section of Trailer preferences: I want to somehow separate out notifications where I am specifically assigned as opposed to a team I am on is assigned. Currently the two categories are lumped together:

<img width="362" alt="Screen Shot 2021-10-18 at 10 59 45 PM" src="https://user-images.githubusercontent.com/3588798/137841956-ce96db36-099e-475e-bd11-43e3421e2337.png">

I'm not sure if the GitHub API even supports this kind of separation; if it doesn't, are there any decent workarounds?

I could see this one dropdown being separated into two, similar to the "Comments" section:

<img width="248" alt="Screen Shot 2021-10-18 at 11 04 55 PM" src="https://user-images.githubusercontent.com/3588798/137842150-885cb955-079a-4d2e-86d5-bfbcb779c51e.png">

**Comment by kamranayub** [comment] 2022-03-11 16:23
Same, we are often requested as a team reviewer but our process is to specifically assign someone to take action (plus the team is removed as soon as one of us reviews).

**Comment by ptsochantaris** [comment] 2023-07-01 17:44
Hi, this makes total sense indeed, and sorry for taking so long to reply. I don't have a ready answer about if the API allows this to be done, but I suspect it does. I'm going to add it to the TODO list with the optimistic expectation that it is possible.

**Comment by ptsochantaris** [comment] 2023-07-29 23:36
Hi, I have implemented a version of this feature in this build - can you try it out and see if it works as intended? (You may have to wait until items have re-synced once for item assignments to re-appear after upgrading.)

[Trailer-185-test-1.zip](https://github.com/ptsochantaris/trailer/files/12208244/Trailer-185-test-1.zip)

**Comment by ptsochantaris** [comment] 2023-08-04 22:46
Hi, this feature is now in the 1.8.5 release: https://github.com/ptsochantaris/trailer/releases/tag/1.8.5 - I'm going to close this issue for now, but please feel free to re-open, or open a new issue if you continue to experience this or other issues.

**Closed by ptsochantaris** 2023-08-04 22:46 UTC
Labels: awaiting feedback
