### ISSUE TITLE
Can't set ...to my teams when there is a new PR

### ISSUE THREAD

**Issue by pokk** [ptsochantaris/trailer#481] opened 2023-08-09 04:57 UTC
version 1.8.5

![2023-08-09-4-55-47](https://github.com/ptsochantaris/trailer/assets/5198104/0f9c7099-916f-4e49-a240-0f246764e971)

I set `Move to Mentioned` and close the preferences window, and open the preference window again. It set back to `Do not Move it`.
Is it possible to take a look at this problem?

**Comment by ptsochantaris** [comment] 2023-08-10 00:12
Whoops, sorry for that, and thanks for spotting it. Will fix! 👍

**Comment by ptsochantaris** [comment] 2023-08-10 08:52
Just checked up on it - the good news is that Trailer will actually remember the choice you made when selecting that value, it's the display of the setting that's broken. I'll do an update shortly to clean this up, thanks again for spotting!

**Comment by ptsochantaris** [comment] 2023-08-10 09:12
Can you give this build a try to see if it resolves the issue for you?

[Trailer-1690.zip](https://github.com/ptsochantaris/trailer/files/12311064/Trailer-1690.zip)

**Comment by ajdafonte** [comment] 2023-08-10 09:31
> Can you give this build a try to see if it resolves the issue for you?

Unfortunately, it does not solve the issue but now the display of the setting is remembered

**Comment by ptsochantaris** [comment] 2023-08-10 10:14
@ajdafonte Thanks for trying it out! I'm glad the setting issue is fixed, but what is the issue you're experiencing exactly? Do you have a good way to reproduce it?

**Comment by pokk** [comment] 2023-08-11 05:32
> Can you give this build a try to see if it resolves the issue for you?
> 
> [Trailer-1690.zip](https://github.com/ptsochantaris/trailer/files/12311064/Trailer-1690.zip)

Thank you so much for the quick response and fix.
It does set correct. However, the actual issue happened to me was 
when I was using `1.8.4`, the team mention did appear to me. `1.8.5` doesn't with the same setting.
And your new build 1690 version seems the same as `1.8.5`.

Could you also please take a look at that issue? 🙇
Appreciated your awesome help

**Comment by pokk** [comment] 2023-08-11 05:33
Another issue happens to me is
Loading never finishes 😭 It is just stuck there and when I rollback to the `1.8.4`, it has the same status

<img width="326" alt="2023-08-11-5-32-33" src="https://github.com/ptsochantaris/trailer/assets/5198104/9067ce21-6189-4d6a-bad9-e2a7485a8f85">

**Comment by pokk** [comment] 2023-08-11 06:05
@ptsochantaris 
Updated, after uninstalled the `1.8.5` and reinstall `1.8.6`, it works well as `1.8.4`

**Comment by ajdafonte** [comment] 2023-08-11 08:26
> @ajdafonte Thanks for trying it out! I'm glad the setting issue is fixed, but what is the issue you're experiencing exactly? Do you have a good way to reproduce it?

I was having the same behaviour as @pokk described [here](https://github.com/ptsochantaris/trailer/issues/481#issuecomment-1674231488), the setting is set correctly in the display, but if a PR is assigned to my team is not displayed at all.

Will have a try again, uninstall and re-install `1.8.6` again to see what happens

**Comment by ajdafonte** [comment] 2023-08-11 08:29
Done, just need to quit and open the app again. Is now working 👍🏼 
Thanks a lot @ptsochantaris 💪🏼

**Comment by ptsochantaris** [comment] 2023-08-11 08:45
Thanks so much for trying it out and the updates, very appreciated. Great to see that the issue _seems_ resolved but let's keep an eye on it and see if it does indeed fix things, or if there's some corner case with the team assignments that I need to dig into 👍 I'll keep this issue open for now so please feel free to give a shout here if you spot anything.

On the issue of the never-ending refresh, it may be the same for this issue: https://github.com/ptsochantaris/trailer/issues/480

If you do encounter that problem again, please do report in that thread, and in particular if, or what, phase of the sync it seems to be perpetually waiting for.

**Comment by ptsochantaris** [comment] 2023-08-17 15:22
Going to close this, if you are having issues with seeing team assignments, please take a look at #485 and see if the latest build improves things.

**Closed by ptsochantaris** 2023-08-17 15:22 UTC
Labels: bug
