### ISSUE TITLE
Since 1.2.0, can no longer swipe away notifications

### ISSUE THREAD

**Issue by orospakr** [ptsochantaris/trailer#177] opened 2015-02-13 19:32 UTC
Normally, OS X notifications can be swiped away by clicking and dragging them off the screen to the right.  In the new version, it always consumes the click and opens up a browser tab.

**Comment by ptsochantaris** [comment] 2015-02-14 11:04
Hi, thanks for calling in an issue!

I can't seem to reproduce this - I've tried dismissing banners both with 1.1.5 and 1.2.0 on my Yosemite system and Mavericks VM, and they seem to dismiss fine (actually I didn't know you could do this, good tip :))

However, I did a bit of research and it seems that OS X will only let you do this on "Banner"-style notifications. If you have set notifications for Trailer to "Alerts" then you have to select their "Close" button to dismiss those, dragging or swiping won't work.

Trailer currently defaults to "Alert" (i.e. the un-swipeable ones) because they stay visible on screen, to ensure users don't miss PR comments or events, but it's easy to change: System Preferences -> Notifications -> Scroll to and select Trailer -> Select "Banners" from the main panel.

Hope this helps. Let me know in case I have misunderstood your issue!

**Comment by Karlotcha** [comment] 2015-02-16 13:51
Hey, I don't know if this is related, but I am on OSX 10.9.5 and it seems notifications are not disappearing anymore automatically :/

**Comment by ptsochantaris** [comment] 2015-02-17 09:24
@Karlotcha try switching them to Banners instead as described above.

**Comment by Karlotcha** [comment] 2015-02-17 10:29
@ptsochantaris yes, banners make it work again, thanks :)

**Comment by ptsochantaris** [comment] 2015-02-19 19:06
Hi, version 1.2.1 is up, which reverts the default back to banner alerts. Will close this issue for now, but please feel free to re-open if you encounter any issues with it.

**Closed by ptsochantaris** 2015-02-19 19:06 UTC
Labels: discussion

**Comment by orospakr** [comment] 2015-02-19 23:29
This explains what happened perfectly.

Thank you very much for your work!
