### ISSUE TITLE
Refreshing large number of repositories hangs during processing Pull Requests

### ISSUE THREAD

**Issue by darend** [ptsochantaris/trailer#480] opened 2023-08-07 22:11 UTC
I upgraded to 1.8.5 and enabled the v4 api and found trailer hangs when refreshing the list of Repositories and Pull Requests

With a clean start trailer needs to crawl ~600 repositories across a few organizations. It makes progress for a few minutes but then stops logging activity and makes no further progress until I quit and reopen. Then it repeats. I monitored the token rate limiting and it is not the issue as shown in the included logs. 

What I observe:
- launch trailer
- logs show activity scanning each repository
- then I believe it moves to fetching pull requests (pullrequestFragment)
- it makes progress for a few minutes then stops
- no additional logs are produced even after an hour
- the menu bar is stuck on "Refresh: Github: Updated PRs (...)"
- opening the settings produces info about the rate limits and they are all good
- every refresh window it logs that a refresh is still in progress
- I need to restart for trailer for it try again

I can not include the full logs publicly because it includes private repository and PR metadata. Here is a snipped from the end as it stopped processing

```
>>> 20230807 14:55:37:010 - Status update: GitHub: Updated PRs (call 25)

>>> 20230807 14:55:37:562 - API data from https://api.github.com/graphql: {
    "data": {
        "nodes": [
            {
                "__typename": "Repository",
                "pullRequests": {
                    "edges": [],
                    "pageInfo": {
                        "hasNextPage": true
                    }
                },
                "id": "R_kgDOExRTrQ"
            }
        ],
        "rateLimit": {
            "limit": 5000,
            "cost": 1,
            "remaining": 4974,
            "resetAt": "2023-08-07T22:50:49Z",
            "nodeCount": 56
        }
    }
}

>>> 20230807 14:55:37:576 - (TQL 'GitHub: Updated PRs') Response time: 0.5664680004119873 sec

>>> 20230807 14:55:37:576 - (TQL 'GitHub: Updated PRs') Received page (Cost: 1, Remaining: 4974/5000 - Expected Count: 56 - Returned Count: 56)

>>> 20230807 14:55:37:576 - (TQL 'GitHub: Updated PRs') Scanning result

>>> 20230807 14:55:37:576 - (TQL 'GitHub: Updated PRs') Parsed all pages

>>> 20230807 14:55:58:236 - API data from https://api.github.com/rate_limit: {"resources":{"core":{"limit":5000,"used":40,"remaining":4960,"reset":1691448653},"search":{"limit":30,"used":0,"remaining":30,"reset":1691445418},"graphql":{"limit":5000,"used":26,"remaining":4974,"reset":1691448649},"integration_manifest":{"limit":5000,"used":0,"remaining":5000,"reset":1691448958},"source_import":{"limit":100,"used":0,"remaining":100,"reset":1691445418},"code_scanning_upload":{"limit":1000,"used":0,"remaining":1000,"reset":1691448958},"actions_runner_registration":{"limit":10000,"used":0,"remaining":10000,"reset":1691448958},"scim":{"limit":15000,"used":0,"remaining":15000,"reset":1691448958},"dependency_snapshots":{"limit":100,"used":0,"remaining":100,"reset":1691445418},"audit_log":{"limit":1750,"used":0,"remaining":1750,"reset":1691448958},"code_search":{"limit":10,"used":0,"remaining":10,"reset":1691445418}},"rate":{"limit":5000,"used":40,"remaining":4960,"reset":1691448653}}

>>> 20230807 14:55:58:246 - (GitHub GET https://api.github.com/rate_limit - RESULT: Success

>>> 20230807 14:56:01:398 - Won't start refresh because refresh is already ongoing


```

**Comment by manfredlift** [comment] 2023-08-09 12:52
Same here. because of that I am not able to get any new PRs into Trailer.

**Comment by ptsochantaris** [comment] 2023-08-10 00:21
Hi, and thanks for reporting this. This is interesting - I can't help but wonder if, because of the large number of repositories, some earlier query is failing and causes the weird bug you're seeing. If you can, do check the full log for any error messages to see if there are any, just in case.

As a workaround (and part of investigating) could you try gradually enabling all the repos? i.e. perhaps 50 or 100 at a time, to see if the issue is perhaps localised to some specific set or subset of the repos?

**Comment by ptsochantaris** [comment] 2023-08-10 00:23
Incidentally, if you feel you are able to share the log via email to me, you can forward it to ptsochantaris at me dot com, and I can try to privately go through it, but absolutely no hard feelings if that's not possible because of private/confidential info in the API data.

**Comment by ptsochantaris** [comment] 2023-08-10 01:01
While we're at it, I have added some extra log messages in this build to signpost the end of each phase - if you get a chance to try it out it will be interesting to see which phase isn't completing.

[Trailer-1689.zip](https://github.com/ptsochantaris/trailer/files/12307875/Trailer-1689.zip)

**Comment by vkuzel** [comment] 2023-08-10 09:49
Note: I've run Trailer from XCode, which (a) seemed to be working just fine, and (b) "did something" to the Trailer's SQLLITE database. Then, I've started Trailer (release) app, which seemed to fetch all data from scratch. Now, everything is working.

Good thing: "Reload All Data" / removing the database in `~/Library/Application Support/com.housetrip.Trailer` may help.
Bad thing: I cannot reproduce the issue now / did not make database backup.

**Comment by ptsochantaris** [comment] 2023-08-10 10:18
Thanks for the update @vkuzel, much appreciated. I wonder if the issue is related to migrating to the new GitHub IDs and creating some sort of infinite loop in some corner cases. Good to know that "reload all data" seems to fix it but I'd still be curious to see if anyone else experiencing this can provide a log of the completed phases to at least start getting a sense of where the hang happens.

**Comment by darend** [comment] 2023-08-10 17:23
@ptsochantaris I used your custom build and was not able to reproduce with this process:
- Marked all repositories as Hide and restarted Trailer
- Waited for trailer to finish refreshing repositories
- Marked 20ish as Participated. It refreshed properly
- Added a few more and it refreshed
- Added a large number
- Added them all

I then a reload all data and also could not reproduce. Lastly I switched back to 1.8.5 and performed a reload all data. This succeeded as well.

**Comment by darend** [comment] 2023-08-10 17:34
I performed one last test. With your custom build I deleted `~/Library/Application Support/com.housetrip.Trailer` and selected all repositories. It performed a complete refresh without issue

**Comment by ptsochantaris** [comment] 2023-08-10 17:57
How incredibly weird, but thank you so much for trying it out and reporting. It's definitely not clear to me if it's the new build or just a matter of resetting the data, but as a precautionary step I'll do a fresh build as a 1.8.6 in case there was some thread locking issue in 1.8.5, plus there's a small fix for prefs which needs shipping - and will continue to keep an eye on this thread.

One request is - if you re-encounter this issue, could you check to see what phase it was that is failing to complete? It may be useful in tracking this issue further should it persist.

Thanks again for testing and reporting, will continue to keep a close eye on this 👍

**Comment by ptsochantaris** [comment] 2023-08-21 20:46
Going to close this for now, but please feel free to re-open or open a new issue if you encounter this or any other problem!

**Closed by ptsochantaris** 2023-08-21 20:46 UTC
Labels: awaiting feedback
