### ISSUE TITLE
Not updating - gets stuck on Refreshing

### ISSUE THREAD

**Issue by danwenzel** [ptsochantaris/trailer#348] opened 2018-02-14 17:59 UTC
I'm having an issue where Trailer is not updating.  I'm seeing older PRs, but X's for the counts next to the top bar icons, and the menu showing `Refreshing...` forever.  Quitting and restarting doesn't seem to work.

I'm in Trailer Version 1.6.6 (1470).  Let me know what other info you need from me, and if you can offer any troubleshooting advice.   Thanks!

**Comment by ptsochantaris** [comment] 2018-02-15 08:33
Hi @danwenzel and thanks for reporting this.

The first step in seeing what may be going wrong is logging Trailer's activity in the console, to see what or if some API call is failing, and why Trailer is not picking the problem up. You can activate it from Preferences -> Misc -> and tick "Log activity to console".

You can then track Trailer's sync activity in Console.app. Give it a try and try to see if some call is failing.

Additionally it may help to deactivate various repos, and see if one specific repo or subset of data is causing Trailer to exhibit the issue, to help test the issue faster.

Another thing to try is to try and disable various options (the most recent build had changes to querying for review stuff, so I would start by completely disabling those options to see if sync completes with them set to off)

If we can track down which call is breaking then it should be easy to see why that is. If you can provide a relatively short log from the sync activity where the issue occurs, I'll be more than happy to go through it and try to see what's "missing" from there.

Finally - when the sync hangs - can you see how many pending operations the app is reporting while the sync has "frozen"? You can see that from the top of the dropdown menu on the top-left of the main Trailer menu.

In any case, sorry you're having this issue - let's see if we can get to the bottom of this!

**Comment by danwenzel** [comment] 2018-02-15 14:50
Thanks for the debugging tips!

It looks like the sync hangs right after some 403 responses, and at that time the Trailer menu goes from reading "Refreshing... (x calls remaining)" to just "Refreshing..."

Here's the end of the log:

```
default	08:40:06.137544 -0600	Trailer	(GitHub) Placing URL https://api.github.com/repos/lytics/ember-data-model-fragments/issues/272/comments?per_page=100 on the throttled list
default	08:40:06.137653 -0600	Trailer	(GitHub) GET https://api.github.com/repos/lytics/ember-data-model-fragments/issues/272/comments?per_page=100 - FAILED: (code 403) Server responded with error 403
default	08:40:39.674986 -0600	Trailer	TIC TCP Conn Cancel [2:0x618000380820]
default	08:40:39.675077 -0600	Trailer	TIC TCP Conn Destroyed [2:0x618000380820]
default	08:40:39.675153 -0600	Trailer	TIC TCP Conn Cancel [3:0x60800019f070]
default	08:40:39.675208 -0600	Trailer	TIC TCP Conn Destroyed [3:0x60800019f070]
default	08:40:39.675255 -0600	Trailer	TIC TCP Conn Cancel [4:0x610000388610]
default	08:40:39.675315 -0600	Trailer	TIC TCP Conn Destroyed [4:0x610000388610]
default	08:40:39.675365 -0600	Trailer	TIC TCP Conn Cancel [5:0x600000384370]
default	08:40:39.675442 -0600	Trailer	TIC TCP Conn Destroyed [5:0x600000384370]
default	08:40:39.675488 -0600	Trailer	TIC TCP Conn Cancel [7:0x600000384510]
default	08:40:39.675531 -0600	Trailer	TIC TCP Conn Destroyed [7:0x600000384510]
default	08:40:39.675572 -0600	Trailer	TIC TCP Conn Cancel [6:0x600000384440]
default	08:40:39.675620 -0600	Trailer	TIC TCP Conn Destroyed [6:0x600000384440]
```

It looks like it's trying to pull some Issues for open source repos that I've filed.  I went ahead and turned all Issues to "Hide" in the preferences, and that seemed to fix the issue.  But it would be nice to be able to see those

**Comment by ptsochantaris** [comment] 2018-02-15 15:04
Ah, that's very useful, thanks for posting it!

That 403 seems to be causing bad behaviour for some reason - the HTTP code is a "permission denied" result. Normally non-200 responses from the API for PRs and Issues will be 404 or 410, which indicate that item is gone.

So the possibilities are that (a) that item is gone but the GitHub API has a new way of expressing it, so I need to make Trailer aware of the new code, or (b) something is wrong with your permissions (i.e. you're not allowed access to that item) and Trailer should be failing the sync with a red "X"

In any case, Trailer should definitely not be "hanging" the sync indefinitely there - I just need to know which "direction" to fix it in (i.e. "item missing" or "permission was -correctly- denied")

To help determine this, can you see if you can view issue 272 in that repo from a browser and let me know what happens?

**Comment by danwenzel** [comment] 2018-02-15 16:01
Yes, I am able to access that issue in the browser: https://github.com/lytics/ember-data-model-fragments/issues/272

In fact, everyone should, as it's a public repo

**Comment by ptsochantaris** [comment] 2018-02-15 17:14
Interesting - so the issue is there, public, and accessible. But the API returns 403. So my first guess is that you may be getting rate-limited for some reason, especially if this is close to the end of the sync - but for whatever reason the sync should fail, so Trailer is sort-of responding to the 403 correctly, but this never seems to complete this sync (in a failed state)

I'll look into why this is happening - thanks for reporting this and for all the feedback. I'll try to get back to you very soon with more info.

**Comment by itsthejb** [comment] 2018-02-27 15:47
Same problem here. Ideally I'd rather just reset settings. Nothing revealing I could find in Console, but that's a bit tricky since Console.app filtering appears to be broken in 10.13.3...

**Comment by ptsochantaris** [comment] 2018-02-27 17:01
Hi @itsthejb are you also seeing an API endpoint hang like that? I know it's a bit of a mess, but if you _can_ take a look at the error code that the failed call provides, it would be a great help.

**Comment by itsthejb** [comment] 2018-02-28 10:10
@ptsochantaris The problem is it's a little hard to search Console.app. I didn't have much luck opening the Trailer app binary directly and logging to the terminal either...

**Comment by spkane** [comment] 2018-03-01 16:13
I'm seeing similar behavior. My instance of Github Enterprise (GHE) is not always available from my laptop, as it is on our corporate network. At least once this has been solved, by connecting to the network and then quitting and restarting Trailer, although I think that I have had times where this did not seem to help.

Maybe at least part of the problem is that it isn't retrying properly when network changes occur?

I've also noticed that I can be on the network, and the API check for "GHE" works fine, but the label for the server is marked in red and the UI is stuck "refreshing".

**Comment by ptsochantaris** [comment] 2018-03-06 08:38
Just to verify, are you sure you're NOT seeing this behaviour with 1.6.5 but seeing it with 1.6.6? If so, the only changes between those two versions has to do with review syncing. Can you try disabling review syncing (temporarily) to see if it fixes the issue? If it does I can zero in on those changes.

**Comment by ptsochantaris** [comment] 2018-03-06 08:54
Ah, I think I may have located the issue, and it IS on the code that's used to fetch reviews. In case of a review assignment API check that fails for some reason, sync will get stuck in limbo. This build contains the fix, which I'll put up as an update asap. It definitely fixes AN issue, and I hope it's specifically THIS issue too :) Please give it a go and let me know if it improves things:

[trailer167.zip](https://github.com/ptsochantaris/trailer/files/1784165/trailer167.zip)

**Comment by danwenzel** [comment] 2018-03-06 16:22
Thanks, @ptsochantaris .  I tried the new version and turned all my Issues back on.  It's still failing, but at least it's telling me now.  After trying to refresh for a bit, it's showing red X's and "Refresh - Last Update Failed"

The console log is below.  I think you may be right, and github may be rate-limiting me, causing the 403s:

```
default	10:20:07.362751 -0600	Trailer	(GitHub) Placing URL https://api.github.com/repos/chrislopresto/ember-freestyle/issues/156/comments?per_page=100 on the throttled list
default	10:20:07.368073 -0600	Trailer	(GitHub) GET https://api.github.com/repos/chrislopresto/ember-freestyle/issues/156/comments?per_page=100 - FAILED: (code 403) Server responded with error 403
default	10:20:07.406269 -0600	Trailer	(GitHub) Placing URL https://api.github.com/repos/emberjs/ember.js/issues/14993/comments?per_page=100 on the throttled list
default	10:20:07.406408 -0600	Trailer	(GitHub) GET https://api.github.com/repos/emberjs/ember.js/issues/14993/comments?per_page=100 - FAILED: (code 403) Server responded with error 403
default	10:20:07.474330 -0600	Trailer	(GitHub) Placing URL https://api.github.com/repos/rwjblue/ember-template-lint/issues/321/comments?per_page=100 on the throttled list
default	10:20:07.474448 -0600	Trailer	(GitHub) GET https://api.github.com/repos/rwjblue/ember-template-lint/issues/321/comments?per_page=100 - FAILED: (code 403) Server responded with error 403
default	10:20:07.775489 -0600	Trailer	Wrapping up sync
default	10:20:07.776249 -0600	Trailer	Rolling back changes for failed sync on API server 'GitHub'
default	10:20:15.285974 -0600	Trailer	Nuked total 0 items marked for deletion
default	10:20:15.333223 -0600	Trailer	Committing synced data
default	10:20:15.339410 -0600	Trailer	Synced data committed
default	10:20:15.347144 -0600	Trailer	Saving DB
default	10:20:15.357745 -0600	Trailer	Refresh done
default	10:20:15.365806 -0600	Trailer	Updating PullRequest menu, X total items
default	10:20:15.365970 -0600	Trailer	Updating PullRequest status item
default	10:20:15.520317 -0600	Trailer	Updating Issue menu, X total items
default	10:20:15.520479 -0600	Trailer	Updating Issue status item
default	10:20:22.683119 -0600	Trailer	TIC TCP Conn Cancel [40:0x600000395200]
default	10:20:22.683214 -0600	Trailer	TIC TCP Conn Destroyed [40:0x600000395200]
default	10:20:22.683279 -0600	Trailer	TIC TCP Conn Cancel [43:0x6180003871c0]
default	10:20:22.683324 -0600	Trailer	TIC TCP Conn Destroyed [43:0x6180003871c0]
default	10:20:22.683372 -0600	Trailer	TIC TCP Conn Cancel [41:0x600000398460]
default	10:20:22.683418 -0600	Trailer	TIC TCP Conn Destroyed [41:0x600000398460]
```

**Comment by ptsochantaris** [comment] 2018-03-06 16:33
Good to hear it's at least "failing properly" now @danwenzel - I agree, I would say that you're probably being rate-limited by GitHub if you have a lot of items getting synced (it's annoying that GitHub has both a rate limit and call limit, and it seems the rate limit is being tightened, I may update Trailer to use slower polling to avoid this in the future if it starts occurring widely). 

Can you try increasing your sync intervals perhaps or reducing the number of repos? 

Sorry if this is a bit vague - can you perhaps try a CURL-based query on one of the above endpoints just after it fails? Just to see what error JSON comes down from the API server.

**Comment by itsthejb** [comment] 2018-03-06 20:51
Thanks all for looking into this! Have not had a chance to lend the help I wanted to. I'll see if I can run in the debugger before the end of the week as well

**Comment by spkane** [comment] 2018-03-07 19:33
I am now running 1.6.7 and so far so good. I will update this if I notice the application getting stuck again.

**Comment by tbutterwith** [comment] 2018-10-02 09:31
Hi, I wanted to note that this issue remains for people using github enterprise. version 1.6.7 works but anything after that hangs on refreshing indefinitely. I can provide logs if needed. Thanks.

**Comment by ptsochantaris** [comment] 2018-10-02 10:34
Hi @tbutterwith and thanks for letting me know. I would very much like to look into this. Could you create a new issue specifically about GitHub Enterprise and attach a log of the API calls made using the latest version (1.6.13)? I'll look into it asap.

**Comment by ptsochantaris** [comment] 2018-10-02 12:10
Just a note - this more recent issue is continued here: https://github.com/ptsochantaris/trailer/issues/372

Closing this specific issue for now.

**Closed by ptsochantaris** 2018-10-02 12:10 UTC
