### ISSUE TITLE
Show notifications only for visible items

### ISSUE THREAD

**Issue by bsiegel** [ptsochantaris/trailer#199] opened 2015-05-04 22:16 UTC
Currently a user receives notifications about all PRs, even when the 'All' section is hidden from the dropdown. It would be nice if notifications were only be shown for visible items.

**Comment by ptsochantaris** [comment] 2015-05-05 08:27
Indeed - oddly enough I thought that was the case already, possibly another regression from the big 1.2 rewrite. Adding this on the things to clean up before the upcoming incremental/cleanup update.

**Comment by ptsochantaris** [comment] 2015-05-05 09:07
This kinda bugged me so I thought I'd patch it up sooner rather than later - have a go with this build and see if it filters out the notifications from "all". Bear in mind that assignment notifications WILL appear, even if they are from the "all" section, because better safe than sorry (although in most cases, if you've hidden the "all" section it's most likely you have "moved assigned PRs to my section" set to "on" anyway)

Have a go and let me know if it improves things for you:
https://www.dropbox.com/s/95d5rub95aihmda/Trailer-notifications.zip?dl=0

**Comment by ptsochantaris** [comment] 2015-05-06 18:12
Version 1.3.2 is up now and should include this feature. I will close this for now, but please feel free to re-open this in case there are issue or problems with it.

**Closed by ptsochantaris** 2015-05-06 18:12 UTC
Labels: bug, in next release
