### ISSUE TITLE
Not all repositories are added while using wildcard for the organisation

### ISSUE THREAD

**Issue by kamilpp** [ptsochantaris/trailer#384] opened 2019-04-01 12:00 UTC
Hey, apologies if this issue has been already reported, I could not find anything related or explain this behaviour.

When I add all repositories from the organisation for another time:

![Screenshot 2019-04-01 at 13 15 30](https://user-images.githubusercontent.com/26869324/55325505-947b4180-5485-11e9-955c-0d8564eb820a.png)

none additional is added (right now there is about 60 listed in `Trailer` app).

My organisation has:

<img width="239" alt="Screenshot 2019-04-01 at 13 55 37" src="https://user-images.githubusercontent.com/26869324/55325694-0f445c80-5486-11e9-872d-4258bdc48530.png">

I was expecting all 238 will get added when I use `*` but it is only ~60.

Does anybody know the explanation?

This one is related and would be good to have: https://github.com/ptsochantaris/trailer/issues/333

**Comment by darend** [comment] 2019-04-01 21:20
Ive encountered the same issue, but have not found a reliable solution

**Comment by ptsochantaris** [comment] 2019-05-05 10:09
Hi, thanks for reporting this - sorry it's taken ages to respond.

I've got a feeling this may be related to paging :) Looking at the code there I don't think the app will react well to multiple pages of repositories returned from the API, so if you have 260 repositories you are trying to add on one go, it will probably fail. I'll try fixing it up so it works well with paged API results and put up a test build shortly.

**Comment by ptsochantaris** [comment] 2019-05-05 10:57
This build should now correctly parse paged repo results from the API - could you give it a go at some point and let me know if it improves things?

[treailer-1493-test.zip](https://github.com/ptsochantaris/trailer/files/3145444/treailer-1493-test.zip)

**Comment by darend** [comment] 2019-05-05 15:13
@ptsochantaris 

I tested it and it immediately imported all of my missing repositories. Thanks!

**Comment by ptsochantaris** [comment] 2019-05-05 15:21
Ah, that's great to know, thank you for the quick feedback!

**Comment by kamilpp** [comment] 2019-05-29 11:12
Hey @ptsochantaris, may I ask when can we expect the release of this? Thanks again :)

**Comment by ptsochantaris** [comment] 2019-05-29 11:20
Hi @kamilpp - I'll send it out as soon as I have a chance to test it a bit. It's taken longer than usual because I'm quite busy these days, but feel free to use the build above, it's definitely a "proper" build. I'll make an effort to push something out this weekend.

**Comment by ptsochantaris** [comment] 2019-06-05 09:08
Hi, this is the current RC for 1.6.17, I'm testing it out currently and hope to put it out to auto-update later on in the week. If you'd care to take it for a spit ahead of time and report any issues, you're very welcome to.

Changelog on macOS:
- New “state:” filtering option (arguments can be: unread/open/closed/merged/snoozed)
- Added simple support for Spotlight in newer macOS versions
- Extra hotkey characters added (thanks to @j-martin)
- Option to (not) include snoozed items in menubar count
- Removed old confusing option to count all open items in watchlist
- Fix for filtering of status items based on included or excluded terms
- Fix for repeat assigned item announcements when first synced
- Fix for adding manual repos using “*” from an org with many repos
- Group labels in preferences repos table properly support copy/paste/undo/redo now
- Built with latest toolchain for performance

[trailer1617.zip](https://github.com/ptsochantaris/trailer/files/3256377/trailer1617.zip)

**Comment by kamilpp** [comment] 2019-06-05 10:29
Sure, testing. If there will be anything misbehaving, I will notify you. Thanks a lot!

**Comment by darend** [comment] 2019-06-17 18:16
@ptsochantaris Ive noticed that the nightly build has an issue where forked repos show up in the Repositories tab twice. Im not sure if this has any other effect. I am getting rate limited when it queries with that build

**Comment by ptsochantaris** [comment] 2019-06-18 08:11
Hi @darend - I don't believe I have touched anything related to syncing repos in this version apart from the import logic for the feature related to this issue. Also, I can't seem to reproduce the issue locally.

If you're seeing a repository twice it's perhaps likely that you've added a server twice or perhaps have it both on your watchlist and have manually added it yourself perhaps? Could it be that you've added two servers, one of which contains a forked version of a repo in the first server perhaps?

Any more info you can provide on this would definitely help me understand more about this!

**Comment by darend** [comment] 2019-06-18 16:43
> If you're seeing a repository twice it's perhaps likely that you've added a server twice or perhaps have it both on your watchlist and have manually added it yourself perhaps? Could it be that you've added two servers, one of which contains a forked version of a repo in the first server perhaps?

Oh, it could be that I had to delete and re-add the github server. Oddly it was only forked repositories that appeared twice.

**Comment by ptsochantaris** [comment] 2019-06-18 17:32
That's interesting to know, I'll check if there was some special reason the forked repositories stuck around, thanks for the update!

**Comment by darend** [comment] 2019-06-18 17:52
> That's interesting to know, I'll check if there was some special reason the forked repositories stuck around, thanks for the update!

I could test it again, if there is a safe way to save then restore my current state before doing so. I know you have the export feature, will it preserve my exact repository/watchlist state? One of the issues I run into is that we have so many repositories, that if I do a clean install it will get rate limited. I have to add repos in batches.

**Comment by darend** [comment] 2019-08-14 18:43
@ptsochantaris when do you plan to do a release with the fix for this issue?

**Comment by ptsochantaris** [comment] 2019-08-14 18:59
Hi @darend I didn't get a chance to test much on the repository issue - have you encountered it again at all? If not I think the RC is good enough to "ship". Let me know and I think I can compile and put an update up very soon.

**Comment by darend** [comment] 2019-08-14 20:02
@ptsochantaris It has not happened again, I say release it.

Thanks!

**Comment by ptsochantaris** [comment] 2019-08-14 20:49
Released: https://github.com/ptsochantaris/trailer/releases/tag/1.6.17 I'll put it on auto-update soon as well.

**Closed** 2019-10-24 07:55 UTC
Labels: Fixed, bug, in next release
