### ISSUE TITLE
Data Sync fails when starting from login

### ISSUE THREAD

**Issue by jamsinclair** [ptsochantaris/trailer#218] opened 2015-08-25 23:04 UTC
I've noticed the past month when trailer starts from login it consistently fails to update it's data. It will display in the options dropdown something like `Refresh - Updated 5394668 seconds ago`. Clicking refresh fails to update as well. Tried deleting trailer and downloading a fresh .dmg. Still the same. 

Quitting the application and opening again solves the update issue when after fresh boot of mac. 

I'll take a screenshot next time I restart my macbook :laughing:. Are there any logs I can access which could be of help?

__Mac Info:__
Version: OSX Yosemite 10.10.4 (14E46)
MacBook Pro (Retina, 15-inch, Mid 2014)

**Comment by ptsochantaris** [comment] 2015-08-26 09:03
Hi @jamsinclair and thanks for reporting this!

A screenshot would be helpful certainly, but you may also want to enable logging from the Misc tab in Trailer for a while. Then, when the issue occurs, you can provide the most recent output from Trailer in Console.app, which should give us a good idea about what is going on there. (I am betting this is sleep-monitoring related, OSX seems to send "mixed signals" about being in a sleep mode - or more possibly the code isn't reading the signals correctly)

With a screenshot, and hopefully some logs around when the issue occurs, we should be able to take some steps and sort this out :+1:

**Comment by jamsinclair** [comment] 2015-08-26 21:37
__What I see after fresh boot of macbook__
<img width="350" alt="screen shot 2015-08-27 at 9 30 41 am" src="https://cloud.githubusercontent.com/assets/5964236/9506904/eeeb1890-4c9e-11e5-88c9-31427ffce03d.png">

__The Logs for trailer when I powered the mac off at night and then booted up in the morning__
<img width="862" alt="screen shot 2015-08-27 at 9 33 57 am" src="https://cloud.githubusercontent.com/assets/5964236/9506929/1f74266e-4c9f-11e5-8df4-fab48a5e5a65.png">

Let me know if I can do anything else to help :smile_cat:

**Comment by ptsochantaris** [comment] 2015-08-26 21:55
Thank you for the feedback @jamsinclair!

This is very interesting, as it looks as if Trailer is starting up before your network connection goes up (which is to be expected in many cases, that's not the problem) but I think it's not taking the fact that your network connection is down into account.

If you scroll further down, do you see a message about "network came up" at all? I'm betting that you probably won't.

This is important, as Trailer, by request of GitHub, features an internal fail-safe "throttle" for repeating failed URL requests. Ofcourse, requests can fail if your network is down, so Trailer will only place failed URL requests in the "throttle box" if it thinks your network connection is up. For some reason here, I think what's happening is:

- Your system powers up and loads the various apps
- Trailer loads up and thinks the network is up, starts a sync
- Sync fails because network isn't up yet
- Trailer puts the URL for your server on the "throttled" list for a few minutes
- Your network comes back up
- Any attempts to sync after that just run into the internal "throttle"

I'm going to have a look at the network detection code and see if/how it falls prey to something like this. I'm currently prepping a point release (see #219) and this could be one of the fixes in the next test build.

Thanks again for the feedback :+1: Please stay tuned, will have more info soon for you on this.

**Comment by jamsinclair** [comment] 2015-08-27 12:03
@ptsochantaris Yup just confirming that a message with something like `network came up` did not appear in the logs as you suspected.

Thanks for looking into this :smile_cat:

**Comment by ptsochantaris** [comment] 2015-08-27 12:07
Ah, good to know :+1: Ok, will be making tweaks to try and get around this, or perhaps to provide more logging of what Trailer thinks you current network state is in the first place and provide a build to get a bit more data on this. I should have a build to test out either tonight (GMT) or tomorrow.

**Comment by ptsochantaris** [comment] 2015-08-27 20:29
Hi @jamsinclair 

Here's a build of the current beta you can try out. It contains the following additional changes:

- Some cleaner network handling code, which only places URLs on the throttled list if the server has responded with an error code, otherwise things like connection failures and/or lack of connectivity should just be regular failures, which can be retried.
- There is more detailed logging if refresh cannot occur - so when you hit Cmd-R you will get feedback in the log file about why nothing is happening, if in fact nothing happens :)
- It logs the initial network status, so we can see what the system is telling the app about your internet connectivity in the first place, when the app starts.

This should at least give us more info to think about the next move. Have a go and let me know if it helps or what info you get from the log.

https://www.dropbox.com/s/ud0cryma25yxila/Trailer-1.3.7-1228-test-2.zip?dl=0

**Comment by jamsinclair** [comment] 2015-08-30 00:15
Thanks for the quick build. Still same problem and not sure whether the logs offer any more info this time. 

Here's two attempts this morning I made with your build 1.3.7 (1228).

__First Attempt with fresh boot:__
<img width="571" alt="screen shot 2015-08-30 at 10 58 27 am" src="https://cloud.githubusercontent.com/assets/5964236/9565088/03df5848-4f0f-11e5-9677-523d39407d49.png">

__Second Attempt with fresh boot:__
<img width="552" alt="screen shot 2015-08-30 at 12 00 05 pm" src="https://cloud.githubusercontent.com/assets/5964236/9565090/132702b0-4f0f-11e5-8d1a-82cb5e067447.png">

**Comment by ptsochantaris** [comment] 2015-08-30 01:08
Hi @jamsinclair 

Thanks for trying it out and providing these logs. Actually there is useful info here, as Trailer is letting us know about what's happening with the network from its perspective.

We can see that Trailer is reading the network connectivity as down and that status never changes (we can also verify that the network is initially down from the fact that the connection to the server fails) So far so good, as networking can come up later on a system just booting up, for instance. What's weird is that Trailer never gets the network availability signal from the OS later on to try again, as it should.

Is there something special about how your network is set up? Are you using straightforward WiFi or are you perhaps using a more exotic setup - networking via 3G, a bluetooth-linked phone or something like that?

If, once your network is up, Trailer has not gotten the message, what happens if you manually disable and then enable your WiFi? Does anything change in Trailer logs?

Let me know on the above and we'll take it from there :+1:

**Comment by jamsinclair** [comment] 2015-08-30 02:36
As far as I'm aware I'm using a straightforward WiFi router setup. Trailer does not log anything when wifi is disabled/re-enabled. When put to sleep and woken up it still thinks network is down.

<img width="571" alt="screen shot 2015-08-30 at 2 35 15 pm" src="https://cloud.githubusercontent.com/assets/5964236/9565458/661231ba-4f24-11e5-8bca-6d75bd4159fc.png">

**Comment by ptsochantaris** [comment] 2015-08-30 09:27
Thanks for updating me, it's good to know it's not a weird interface issue :)

So, yes, for some crazy reason the Reachability class isn't doing it's work correctly on your system - changes to the network state are never reported dynamically. Interestingly enough though, Trailer DOES seem to get the right network state when starting up, so when it starts off during login it sees "Down" but if you restart it later on it sees "Up".

To answer your question, there may be software which you are running or configuration of your network services that may be causing this, or there may be strange corner-case caveats to network availability detection which I am not covering properly (I'm using a custom version of Apple's Reachability class)

So my instinct is to, initially, try and double-check network availability, i.e. at the point where you get errors like "won't refresh because network is down" the app will check availability the same way it checked when it started up (which ought not to make a difference, but it seems to!).

This won't fix the issue of Trailer syncing as soon as network is up, but if it works it will at least fix your "permanently frozen sync" issue, as Trailer will check at the refresh interval it's set to in every case. Then we can move on to see about making it properly dynamic so it syncs up as soon as you have network.

Here is a build with that double-check step in place, give it a shot and let me know if there is any improvement.

https://www.dropbox.com/s/w0zpt83xpzhhtci/Trailer-1.3.7-1228-test-network-1.zip?dl=0

If it works, then you should see the logs as they are now, but once your network is up, hit Cmd-R for refresh (or just wait for the interval you have configured) and see if the "won't start refresh because internet connectivity is down" situation improves.

**Comment by jamsinclair** [comment] 2015-09-01 10:58
Sorry for the delay and thanks for the newer build to test, unfortunately no luck with it. After waiting a few minutes after startup and manually triggering a refresh with Cmd-R still logging `Won't  start refresh because internet connectivity is down`.

**Comment by ptsochantaris** [comment] 2015-09-01 11:09
No worries about time, thanks for testing in the first place! What's the feedback you get about detecting network availability just before you get to the "won't start refresh" message? There should be more info starting with "Actively verifying reported network availability state". Does it state "no change to network state"? If so, I'll provide a new build with an even "harder" network detection reset and we can see what happens.

**Comment by jamsinclair** [comment] 2015-09-01 11:13
Was totally running wrong version, deleted the other trailer app build from fs and tried again. 

Amazing :+1:, that newer build seems to have fixed the problem, it recognises network is up on first go, or so it seems from the logs. 

<img width="675" alt="screen shot 2015-09-01 at 23 10 48" src="https://cloud.githubusercontent.com/assets/5964236/9602710/caff8182-50fe-11e5-879a-d84d3098ff42.png">

**Comment by ptsochantaris** [comment] 2015-09-01 11:55
Great to hear this is working for you! :+1: 

What's interesting is that I didn't really tweak that initial detection at all (just shifted it around a bit in order to add the verification logic, but there were no logic changes in the initial detection step. I wonder if it was running into a corner case related to Swift initialisation...)

I'm thinking of keeping that extra network state verification step there as well, just in case.

I'll update the "main" beta with this code and another minor feature from another issue later on today, if you feel like continuing to run this test build you may want to keep an eye on the beta issue thread's updates, to make sure you have as stable a beta as possible.

Anyway, let's keep an eye on this for the next few days, let me know if it stops working or in case this was a one-off (hopefully not :)) and once again, thanks for reporting this and testing!

**Comment by jamsinclair** [comment] 2015-09-01 12:45
Brilliant, will keep an eye on it :+1:

**Comment by jamsinclair** [comment] 2015-09-06 21:31
Been using 1.3.7 Beta Build 3 (1230) the last few days and every time on boot it's recognising the network is up. Thanks so much for the fix!!

**Comment by ptsochantaris** [comment] 2015-09-07 20:17
That's really great to know, thanks for testing @jamsinclair :+1: 

I have to admit, even though I am not too proud to say it, I am still puzzled as to *why* this has started working, and will chalk it up to the way Swift binaries initialise ObjC objects, plus I will be sure to keep the Reachability initialisation that way to ensure this does not regress in the future. That said, if you ever see this re-occuring please DO open a new issue or re-open this one.

I will leave this open until the final release of 1.3.7 in case anyone else has the same issue and will close it afterwards.

Thank you again for reporting this, and your help in helping to locate and correct it!

**Comment by ptsochantaris** [comment] 2015-09-13 22:31
Hi, Version 1.3.7 for OSX is now up which includes this fix (and should be more stable than the betas you are currently running) You can auto-update from any beta or previous version from the About window. Please feel free to open further issues if you encounter this problem again in the future or spot any further regressions.

**Closed by ptsochantaris** 2015-09-13 22:31 UTC
Labels: bug, in next release
