### ISSUE TITLE
Constant "Refreshing ..." indicator

### ISSUE THREAD

**Issue by aik099** [ptsochantaris/trailer#225] opened 2015-10-14 06:15 UTC
On first run Trailer refreshes properly and shows PR count. But then on next refresh process hangs (as if GitHub wasn't responding) and I got "X" instead PR count all the time.

The GitHub API status shows that all is fine.

![trailer_hangs](https://cloud.githubusercontent.com/assets/1277526/10476186/2c165222-7254-11e5-91cd-1dba027b56d1.png)

Output from Console (when logging enabled):

```
10/14/15 10:22:43.425 Trailer[72636]: (GitHub) GET https:/api.github.com/users/aik099/received_events?per_page=100&page=1 - FAILED: Server did not repond
10/14/15 10:22:44.423 Trailer[72636]: (GitHub) GET https:/api.github.com/users/aik099/events?per_page=100&page=1 - FAILED: Server did not repond
10/14/15 10:22:44.427 Trailer[72636]: Rolling back changes for failed sync on API server 'GitHub'
```

**Comment by ptsochantaris** [comment] 2015-10-14 08:59
Hi @aik099 

Interesting! Some things to check:

From the console message it seems the API server just timed out for whatever reason - entirely possible the GitHub API was down for a short period? Do subsequent refreshes work, or is it always the first sync after starting the app that works fine but the subsequent ones don't?

Also, what does your API usage percentage look like? Is it perhaps above the limit?

Are there any proxy settings in between you and GitHub? Something may be interfering with the 304 "no new change" responses from the two event endpoints perhaps.

The refresh option staying grey after the sync failure definitely looks like a bug though! Will check that out ASAP.

**Comment by aik099** [comment] 2015-10-14 09:31
> Do subsequent refreshes work, or is it always the first sync after starting the app that works fine but the subsequent ones don't?

Subsequent refreshes work the same - hangs for several minutes. I've tried and it works now. Very strange. Maybe GitHub has API service outages in some regions only and that wasn't shown on status page. Also at that time I had problems posting an issue comment - after pressing "Submit" button the comment wasn't posted and Submit button (on GitHub) was grayed out. It only happened with GitHub, because YouTube for example had no issues at same time, when GitHub did.

> Also, what does your API usage percentage look like? Is it perhaps above the limit?

Never paid attention to it. Does this mean 0% used or 100% used:
![trailer_githubusagepercent](https://cloud.githubusercontent.com/assets/1277526/10479816/2876ca50-726f-11e5-9993-5fbda8e65d48.png)

> Are there any proxy settings in between you and GitHub? Something may be interfering with the 304 "no new change" responses from the two event endpoints perhaps.

Not, that I'm aware of. These problems only started to happen at the end of last week.

> The refresh option staying grey after the sync failure definitely looks like a bug though! Will check that out ASAP.

Good. Maybe you can also set a smaller connection timeout, because right now waiting for several minutes for GitHub to respond isn't a good idea. If GItHub is down, then no point in waiting too long.

**Comment by ptsochantaris** [comment] 2015-10-14 09:45
Yes, that's 0% - 100% would be full and red :) Also, Trailer will nag you about it when your percentage gets close to high.

About timeouts, I'm not sure if it's wise to mess with default system timings, as not all connections are over sturdy Ethernet or WiFi.

Will look more into the grayed-out refresh issue though which is the one thing that signals something is going weird in your connection - perhaps this will lead us to more clues about what is going wrong.

**Comment by aik099** [comment] 2015-10-14 10:36
> which is the one thing that signals something is going weird in your connection

Maybe that's weird Wi-Fi problem, that is known to some Yosemite users. Strangely disabling and enabling Wi-Fi did help for some time, but then problem returned.

**Comment by ptsochantaris** [comment] 2015-10-22 22:47
Hi, I've had a look at this, simulating the same failure that you got above, but I couldn't reproduce the stuck "Refreshing" indicator. Could you try this intermediate test build to see if it improves things?

https://www.dropbox.com/s/777yhlnlco6qphi/Trailer-1.3.9-test-1.zip?dl=0

**Comment by ptsochantaris** [comment] 2015-10-22 23:09
Here is a new link with a fix :) https://www.dropbox.com/s/goqmpmtau4w8p2d/Trailer-1.3.9-test-2.zip?dl=0

**Comment by ptsochantaris** [comment] 2015-10-23 00:13
That actually just went to release, so you can get 1.3.9 from here: https://github.com/ptsochantaris/trailer/releases

**Comment by aik099** [comment] 2015-10-23 12:49
I'm not sure if that was intentional or not, but after update Trailer seems to have forgotten all my settings, including GitHub access token.

**Comment by ptsochantaris** [comment] 2015-10-23 12:56
It wasn't unfortunately - I've had this reported by another user as well, but I think they were on 1.3.6 - Do you remember which version you were migrating from? Was it 1.3.7 or earlier? If you migrate over more than one version (i.e. 1.3.6 or older) there's a chance Trailer may reset the database.

I try to keep database migrations to a minimum across versions to avoid this, but unfortunately like in this case, skipping two versions with consecutive migrations could end up causing this.

(Also, the bug you were reporting earlier may have been due to you running an older version)

Really sorry about this, I hope it's not too much of a chore to set up your settings again :(

**Comment by aik099** [comment] 2015-10-23 13:03
Yes, I was on 1.3.7 version exactly. So if restore it from Trash, where upgrade process moved it I'll my settings again?

I guess I'll try to set all settings. What would be really hard is to remember what repos I've disabled in Trailer but was watching on GitHub.

**Comment by ptsochantaris** [comment] 2015-10-23 13:30
This is a bit worrying, 1.3.7 to 1.3.9 should not have done that - I'm going to check it ASAP

**Comment by ptsochantaris** [comment] 2015-10-23 13:35
Oh, and to answer your questions, unfortunately no, your repo settings have been lost, as they were stored in the database which was reset. :(

**Comment by aik099** [comment] 2015-10-23 13:44
I'm not sure how database upgrade happens in Mac app world, but in PHP world (I'm PHP developer) it's best to do 1.3.7 to 1.38 and then 1.3.8 to 1.3.9 instead of direct 1.3.7 to 1.3.9.

**Comment by ptsochantaris** [comment] 2015-10-23 13:48
True, although there wasn't a 1.3.8 in this case (that was iOS only) - however I am still puzzled about this, because I just tried a full clean setup of 1.3.7 and upgraded to 1.3.9 without issue. I'm not sure what it didn't "like" about you installation.

**Comment by aik099** [comment] 2015-10-23 13:52
If an upgrade log is written somewhere, then I can post it here if you need.

Regardless original problem (stuck refreshing indicator). Right now GitHub seems work fine and that's why I can't tell if the issue was fixed.

**Comment by ptsochantaris** [comment] 2015-10-23 13:57
Yeah, no problem on that - let me know in case you spot it again.

As for the update log - there will be something in your logs about the DB failing and getting reset, but I am not sure if there is any useful info there, the Core Data messages are a bit opaque.

**Comment by ptsochantaris** [comment] 2015-10-23 14:08
I can't quite get my head around it - Just tested 1.3.6 -> 1.3.9 and that works as well. Which means *something else* broke on your update (unless you're wrong and you were on an ancient version, but I doubt it), which makes me worry a bit. If you get a chance to check out Console.log, have a look around the time of the update, and if there are any errors or suspicious messages from Trailer, let me know.

**Comment by ptsochantaris** [comment] 2015-10-23 14:17
Hm, it just occurred to me, there IS one way to get your settings back if you have Time Machine or another backup of your ~/Library/Application Support directory before the update!

1) Download Trailer 1.3.7
2) Restore the old com.housetrip.Trailer directory from before your update in ~/Library/Application Support
3) Export your settings from Preferences
4) Install 1.3.9 (which I assume will break stuff)
5) Import your old settings

That should do it. I hope this helps!

**Comment by aik099** [comment] 2015-10-23 15:37
Here is the log:
```
10/23/15 15:36:57.870 Trailer[465]: Sparkle: ===== Trailer =====
10/23/15 15:37:01.964 Trailer[465]: Sparkle: Extracting /Users/alex/Library/Application Support/Trailer/.Sparkle/Trailer 1246 2/trailer139.zip using 'ditto -x -k - "$DESTINATION"'
10/23/15 15:37:14.218 Trailer[465]: Performance: Please update this scripting addition to supply a value for ThreadSafe for each event handler: "/Library/ScriptingAdditions/PresentationModeSA.osax"
10/23/15 15:37:14.219 Trailer[465]: Performance: Please update this scripting addition to supply a value for ThreadSafe for each event handler: "/Library/ScriptingAdditions/SIMBL.osax"
10/23/15 15:37:14.579 Trailer[465]: Bartender: Loaded BartenderHelperNinetySix
10/23/15 15:43:06.969 Trailer[454]: Sparkle: ===== Trailer =====
10/23/15 15:43:15.574 Trailer[454]: Sparkle: Extracting /Users/alex/Library/Application Support/Trailer/.Sparkle/Trailer 1246 3/trailer139.zip using 'ditto -x -k - "$DESTINATION"'
10/23/15 15:43:16.332 Trailer[454]: Performance: Please update this scripting addition to supply a value for ThreadSafe for each event handler: "/Library/ScriptingAdditions/PresentationModeSA.osax"
10/23/15 15:43:16.333 Trailer[454]: Performance: Please update this scripting addition to supply a value for ThreadSafe for each event handler: "/Library/ScriptingAdditions/SIMBL.osax"
10/23/15 15:43:16.346 Trailer[454]: Bartender: Loaded BartenderHelperNinetySix
10/23/15 15:43:28.711 Trailer[454]: Sparkle: ===== Trailer =====
10/23/15 15:43:41.254 Trailer[454]: Sparkle: Extracting /Users/alex/Library/Application Support/Trailer/.Sparkle/Trailer 1246 3/trailer139.zip using 'ditto -x -k - "$DESTINATION"'
10/23/15 15:43:42.000 kernel[0]: Trailer[454] Unable to quarantine: 93
10/23/15 15:43:42.000 kernel[0]: Trailer[454] Unable to quarantine: 93
10/23/15 15:43:42.000 kernel[0]: Trailer[454] Unable to quarantine: 93
10/23/15 15:43:42.000 kernel[0]: Trailer[454] Unable to quarantine: 93
10/23/15 15:43:42.000 kernel[0]: Trailer[454] Unable to quarantine: 93
10/23/15 15:43:42.000 kernel[0]: Trailer[454] Unable to quarantine: 93
10/23/15 15:43:42.000 kernel[0]: Trailer[454] Unable to quarantine: 93
10/23/15 15:43:42.000 kernel[0]: Trailer[454] Unable to quarantine: 93
10/23/15 15:43:42.000 kernel[0]: Trailer[454] Unable to quarantine: 93
10/23/15 15:43:42.000 kernel[0]: Trailer[454] Unable to quarantine: 93
10/23/15 15:43:42.000 kernel[0]: Trailer[454] Unable to quarantine: 93
10/23/15 15:43:42.000 kernel[0]: Trailer[454] Unable to quarantine: 93
10/23/15 15:43:42.000 kernel[0]: Trailer[454] Unable to quarantine: 93
10/23/15 15:43:43.697 Trailer[551]: CoreData: error: -addPersistentStoreWithType:SQLite configuration:(null) URL:file:///Users/alex/Library/Application%20Support/com.housetrip.Trailer/Trailer.sqlite options:{
    NSInferMappingModelAutomaticallyOption = 1;
    NSMigratePersistentStoresAutomaticallyOption = 1;
    NSSQLitePragmasOption =     {
        fullfsync = 0;
        synchronous = OFF;
    };
} ... returned error Error Domain=NSCocoaErrorDomain Code=134130 "Persistent store migration failed, missing source managed object model." UserInfo=0x610000267600 {URL=file:///Users/alex/Library/Application%20Support/com.housetrip.Trailer/Trailer.sqlite, metadata={
    NSPersistenceFrameworkVersion = 526;
    NSStoreModelVersionHashes =     {
        ApiServer = <613c28fa f60126c2 7248ede0 7f9eb166 84f11684 9d3893ef e4efffbd 0fb2460f>;
        Issue = <57fd9c9c 2952534c a6692218 9720afb8 34f64a3b d1cce998 c54a7b46 91276b65>;
        PRComment = <f6e4d588 6fd9b7be df091e02 b600c30d 438194ca a797c230 b5503d78 eb2771ba>;
        PRLabel = <01be39e0 dd12854c bc9e9ee6 73ba8a87 719ac8cd ed58f415 d75abfaa 746dc3c7>;
        PRStatus = <57e54bc1 105a7f9d a6936774 cc798594 58a49789 60a7366f 766812ff cda971ea>;
        PullRequest = <6964fceb cccbc4af 5f24e03a 9ecfea1d 21319ead 83104587 9d5a7e1e 566f460a>;
        Repo = <54b13390 937a7699 d317b3a3 e123b15e 735500c6 ec52ff39 601075e5 6b60636a>;
        Team = <a505e862 fd7ed3ca 250614cd 2a7f8391 9c06e668 15b1b6a0 b17dfb90 f22ee5a8>;
    };
    NSStoreModelVersionHashesVersion = 3;
    NSStoreModelVersionIdentifiers =     (
        ""
    );
    NSStoreType = SQLite;
    NSStoreUUID = "77CC5419-48E1-4CC4-809F-A5A5322EFA27";
    "_NSAutoVacuumLevel" = 2;
}, reason=Can't find model for source store} with userInfo dictionary {
    URL = "file:///Users/alex/Library/Application%20Support/com.housetrip.Trailer/Trailer.sqlite";
    metadata =     {
        NSPersistenceFrameworkVersion = 526;
        NSStoreModelVersionHashes =         {
            ApiServer = <613c28fa f60126c2 7248ede0 7f9eb166 84f11684 9d3893ef e4efffbd 0fb2460f>;
            Issue = <57fd9c9c 2952534c a6692218 9720afb8 34f64a3b d1cce998 c54a7b46 91276b65>;
            PRComment = <f6e4d588 6fd9b7be df091e02 b600c30d 438194ca a797c230 b5503d78 eb2771ba>;
            PRLabel = <01be39e0 dd12854c bc9e9ee6 73ba8a87 719ac8cd ed58f415 d75abfaa 746dc3c7>;
            PRStatus = <57e54bc1 105a7f9d a6936774 cc798594 58a49789 60a7366f 766812ff cda971ea>;
            PullRequest = <6964fceb cccbc4af 5f24e03a 9ecfea1d 21319ead 83104587 9d5a7e1e 566f460a>;
            Repo = <54b13390 937a7699 d317b3a3 e123b15e 735500c6 ec52ff39 601075e5 6b60636a>;
            Team = <a505e862 fd7ed3ca 250614cd 2a7f8391 9c06e668 15b1b6a0 b17dfb90 f22ee5a8>;
        };
        NSStoreModelVersionHashesVersion = 3;
        NSStoreModelVersionIdentifiers =         (
            ""
        );
        NSStoreType = SQLite;
        NSStoreUUID = "77CC5419-48E1-4CC4-809F-A5A5322EFA27";
        "_NSAutoVacuumLevel" = 2;
    };
    reason = "Can't find model for source store";
}
10/23/15 15:43:43.698 Trailer[551]: CoreData: annotation: NSPersistentStoreCoordinator's current model hashes are {
    ApiServer = <613c28fa f60126c2 7248ede0 7f9eb166 84f11684 9d3893ef e4efffbd 0fb2460f>;
    Issue = <d7468c64 a94a9731 a56d040f 1033d5a6 f097394c b96a33ab a10e9b13 1abe02b5>;
    PRComment = <f6e4d588 6fd9b7be df091e02 b600c30d 438194ca a797c230 b5503d78 eb2771ba>;
    PRLabel = <01be39e0 dd12854c bc9e9ee6 73ba8a87 719ac8cd ed58f415 d75abfaa 746dc3c7>;
    PRStatus = <57e54bc1 105a7f9d a6936774 cc798594 58a49789 60a7366f 766812ff cda971ea>;
    PullRequest = <13ffa74d b7144ef6 ce405e14 1481ff3f 189e396c b5fed708 07b4d4ac d80828e2>;
    Repo = <54b13390 937a7699 d317b3a3 e123b15e 735500c6 ec52ff39 601075e5 6b60636a>;
    Team = <a505e862 fd7ed3ca 250614cd 2a7f8391 9c06e668 15b1b6a0 b17dfb90 f22ee5a8>;
}
10/23/15 15:43:52.334 Trailer[551]: Performance: Please update this scripting addition to supply a value for ThreadSafe for each event handler: "/Library/ScriptingAdditions/PresentationModeSA.osax"
10/23/15 15:43:52.335 Trailer[551]: Performance: Please update this scripting addition to supply a value for ThreadSafe for each event handler: "/Library/ScriptingAdditions/SIMBL.osax"
10/23/15 15:43:52.342 Trailer[551]: Bartender: Loaded BartenderHelperNinetySix
10/23/15 16:04:33.786 Trailer[1918]: CoreData: error: -addPersistentStoreWithType:SQLite configuration:(null) URL:file:///Users/alex/Library/Application%20Support/com.housetrip.Trailer/Trailer.sqlite options:{
    NSInferMappingModelAutomaticallyOption = 1;
    NSMigratePersistentStoresAutomaticallyOption = 1;
    NSSQLitePragmasOption =     {
        fullfsync = 0;
        synchronous = OFF;
    };
} ... returned error Error Domain=NSCocoaErrorDomain Code=134130 "Persistent store migration failed, missing source managed object model." UserInfo=0x61000006d080 {URL=file:///Users/alex/Library/Application%20Support/com.housetrip.Trailer/Trailer.sqlite, metadata={
    NSPersistenceFrameworkVersion = 526;
    NSStoreModelVersionHashes =     {
        ApiServer = <613c28fa f60126c2 7248ede0 7f9eb166 84f11684 9d3893ef e4efffbd 0fb2460f>;
        Issue = <d7468c64 a94a9731 a56d040f 1033d5a6 f097394c b96a33ab a10e9b13 1abe02b5>;
        PRComment = <f6e4d588 6fd9b7be df091e02 b600c30d 438194ca a797c230 b5503d78 eb2771ba>;
        PRLabel = <01be39e0 dd12854c bc9e9ee6 73ba8a87 719ac8cd ed58f415 d75abfaa 746dc3c7>;
        PRStatus = <57e54bc1 105a7f9d a6936774 cc798594 58a49789 60a7366f 766812ff cda971ea>;
        PullRequest = <13ffa74d b7144ef6 ce405e14 1481ff3f 189e396c b5fed708 07b4d4ac d80828e2>;
        Repo = <54b13390 937a7699 d317b3a3 e123b15e 735500c6 ec52ff39 601075e5 6b60636a>;
        Team = <a505e862 fd7ed3ca 250614cd 2a7f8391 9c06e668 15b1b6a0 b17dfb90 f22ee5a8>;
    };
    NSStoreModelVersionHashesVersion = 3;
    NSStoreModelVersionIdentifiers =     (
        ""
    );
    NSStoreType = SQLite;
    NSStoreUUID = "AAC92835-E5BB-4D56-9C4B-6CABB9FFC675";
    "_NSAutoVacuumLevel" = 2;
}, reason=Can't find model for source store} with userInfo dictionary {
    URL = "file:///Users/alex/Library/Application%20Support/com.housetrip.Trailer/Trailer.sqlite";
    metadata =     {
        NSPersistenceFrameworkVersion = 526;
        NSStoreModelVersionHashes =         {
            ApiServer = <613c28fa f60126c2 7248ede0 7f9eb166 84f11684 9d3893ef e4efffbd 0fb2460f>;
            Issue = <d7468c64 a94a9731 a56d040f 1033d5a6 f097394c b96a33ab a10e9b13 1abe02b5>;
            PRComment = <f6e4d588 6fd9b7be df091e02 b600c30d 438194ca a797c230 b5503d78 eb2771ba>;
            PRLabel = <01be39e0 dd12854c bc9e9ee6 73ba8a87 719ac8cd ed58f415 d75abfaa 746dc3c7>;
            PRStatus = <57e54bc1 105a7f9d a6936774 cc798594 58a49789 60a7366f 766812ff cda971ea>;
            PullRequest = <13ffa74d b7144ef6 ce405e14 1481ff3f 189e396c b5fed708 07b4d4ac d80828e2>;
            Repo = <54b13390 937a7699 d317b3a3 e123b15e 735500c6 ec52ff39 601075e5 6b60636a>;
            Team = <a505e862 fd7ed3ca 250614cd 2a7f8391 9c06e668 15b1b6a0 b17dfb90 f22ee5a8>;
        };
        NSStoreModelVersionHashesVersion = 3;
        NSStoreModelVersionIdentifiers =         (
            ""
        );
        NSStoreType = SQLite;
        NSStoreUUID = "AAC92835-E5BB-4D56-9C4B-6CABB9FFC675";
        "_NSAutoVacuumLevel" = 2;
    };
    reason = "Can't find model for source store";
}
10/23/15 16:04:33.787 Trailer[1918]: CoreData: annotation: NSPersistentStoreCoordinator's current model hashes are {
    ApiServer = <613c28fa f60126c2 7248ede0 7f9eb166 84f11684 9d3893ef e4efffbd 0fb2460f>;
    Issue = <57fd9c9c 2952534c a6692218 9720afb8 34f64a3b d1cce998 c54a7b46 91276b65>;
    PRComment = <f6e4d588 6fd9b7be df091e02 b600c30d 438194ca a797c230 b5503d78 eb2771ba>;
    PRLabel = <01be39e0 dd12854c bc9e9ee6 73ba8a87 719ac8cd ed58f415 d75abfaa 746dc3c7>;
    PRStatus = <57e54bc1 105a7f9d a6936774 cc798594 58a49789 60a7366f 766812ff cda971ea>;
    PullRequest = <6964fceb cccbc4af 5f24e03a 9ecfea1d 21319ead 83104587 9d5a7e1e 566f460a>;
    Repo = <54b13390 937a7699 d317b3a3 e123b15e 735500c6 ec52ff39 601075e5 6b60636a>;
    Team = <a505e862 fd7ed3ca 250614cd 2a7f8391 9c06e668 15b1b6a0 b17dfb90 f22ee5a8>;
}
10/23/15 16:04:34.011 Trailer[1918]: Sparkle: ===== Trailer (1236) =====
10/23/15 16:04:40.122 Trailer[1918]: tcp_connection_destination_prepare_complete 1 connectx to 185.31.17.133:80@0 failed: Host is down
10/23/15 16:04:40.281 Trailer[1918]: Performance: Please update this scripting addition to supply a value for ThreadSafe for each event handler: "/Library/ScriptingAdditions/PresentationModeSA.osax"
10/23/15 16:04:40.282 Trailer[1918]: Performance: Please update this scripting addition to supply a value for ThreadSafe for each event handler: "/Library/ScriptingAdditions/SIMBL.osax"
10/23/15 16:04:40.290 Trailer[1918]: Bartender: Loaded BartenderHelperNinetySix
10/23/15 16:05:03.271 Trailer[1947]: CoreData: error: -addPersistentStoreWithType:SQLite configuration:(null) URL:file:///Users/alex/Library/Application%20Support/com.housetrip.Trailer/Trailer.sqlite options:{
    NSInferMappingModelAutomaticallyOption = 1;
    NSMigratePersistentStoresAutomaticallyOption = 1;
    NSSQLitePragmasOption =     {
        fullfsync = 0;
        synchronous = OFF;
    };
} ... returned error Error Domain=NSCocoaErrorDomain Code=134130 "Persistent store migration failed, missing source managed object model." UserInfo=0x600000262980 {URL=file:///Users/alex/Library/Application%20Support/com.housetrip.Trailer/Trailer.sqlite, metadata={
    NSPersistenceFrameworkVersion = 526;
    NSStoreModelVersionHashes =     {
        ApiServer = <613c28fa f60126c2 7248ede0 7f9eb166 84f11684 9d3893ef e4efffbd 0fb2460f>;
        Issue = <57fd9c9c 2952534c a6692218 9720afb8 34f64a3b d1cce998 c54a7b46 91276b65>;
        PRComment = <f6e4d588 6fd9b7be df091e02 b600c30d 438194ca a797c230 b5503d78 eb2771ba>;
        PRLabel = <01be39e0 dd12854c bc9e9ee6 73ba8a87 719ac8cd ed58f415 d75abfaa 746dc3c7>;
        PRStatus = <57e54bc1 105a7f9d a6936774 cc798594 58a49789 60a7366f 766812ff cda971ea>;
        PullRequest = <6964fceb cccbc4af 5f24e03a 9ecfea1d 21319ead 83104587 9d5a7e1e 566f460a>;
        Repo = <54b13390 937a7699 d317b3a3 e123b15e 735500c6 ec52ff39 601075e5 6b60636a>;
        Team = <a505e862 fd7ed3ca 250614cd 2a7f8391 9c06e668 15b1b6a0 b17dfb90 f22ee5a8>;
    };
    NSStoreModelVersionHashesVersion = 3;
    NSStoreModelVersionIdentifiers =     (
        ""
    );
    NSStoreType = SQLite;
    NSStoreUUID = "1BCB0AD1-A6FE-4175-8F99-069B45F85535";
    "_NSAutoVacuumLevel" = 2;
}, reason=Can't find model for source store} with userInfo dictionary {
    URL = "file:///Users/alex/Library/Application%20Support/com.housetrip.Trailer/Trailer.sqlite";
    metadata =     {
        NSPersistenceFrameworkVersion = 526;
        NSStoreModelVersionHashes =         {
            ApiServer = <613c28fa f60126c2 7248ede0 7f9eb166 84f11684 9d3893ef e4efffbd 0fb2460f>;
            Issue = <57fd9c9c 2952534c a6692218 9720afb8 34f64a3b d1cce998 c54a7b46 91276b65>;
            PRComment = <f6e4d588 6fd9b7be df091e02 b600c30d 438194ca a797c230 b5503d78 eb2771ba>;
            PRLabel = <01be39e0 dd12854c bc9e9ee6 73ba8a87 719ac8cd ed58f415 d75abfaa 746dc3c7>;
            PRStatus = <57e54bc1 105a7f9d a6936774 cc798594 58a49789 60a7366f 766812ff cda971ea>;
            PullRequest = <6964fceb cccbc4af 5f24e03a 9ecfea1d 21319ead 83104587 9d5a7e1e 566f460a>;
            Repo = <54b13390 937a7699 d317b3a3 e123b15e 735500c6 ec52ff39 601075e5 6b60636a>;
            Team = <a505e862 fd7ed3ca 250614cd 2a7f8391 9c06e668 15b1b6a0 b17dfb90 f22ee5a8>;
        };
        NSStoreModelVersionHashesVersion = 3;
        NSStoreModelVersionIdentifiers =         (
            ""
        );
        NSStoreType = SQLite;
        NSStoreUUID = "1BCB0AD1-A6FE-4175-8F99-069B45F85535";
        "_NSAutoVacuumLevel" = 2;
    };
    reason = "Can't find model for source store";
}
10/23/15 16:05:03.272 Trailer[1947]: CoreData: annotation: NSPersistentStoreCoordinator's current model hashes are {
    ApiServer = <613c28fa f60126c2 7248ede0 7f9eb166 84f11684 9d3893ef e4efffbd 0fb2460f>;
    Issue = <d7468c64 a94a9731 a56d040f 1033d5a6 f097394c b96a33ab a10e9b13 1abe02b5>;
    PRComment = <f6e4d588 6fd9b7be df091e02 b600c30d 438194ca a797c230 b5503d78 eb2771ba>;
    PRLabel = <01be39e0 dd12854c bc9e9ee6 73ba8a87 719ac8cd ed58f415 d75abfaa 746dc3c7>;
    PRStatus = <57e54bc1 105a7f9d a6936774 cc798594 58a49789 60a7366f 766812ff cda971ea>;
    PullRequest = <13ffa74d b7144ef6 ce405e14 1481ff3f 189e396c b5fed708 07b4d4ac d80828e2>;
    Repo = <54b13390 937a7699 d317b3a3 e123b15e 735500c6 ec52ff39 601075e5 6b60636a>;
    Team = <a505e862 fd7ed3ca 250614cd 2a7f8391 9c06e668 15b1b6a0 b17dfb90 f22ee5a8>;
}
10/23/15 16:05:16.612 Trailer[1947]: Performance: Please update this scripting addition to supply a value for ThreadSafe for each event handler: "/Library/ScriptingAdditions/PresentationModeSA.osax"
10/23/15 16:05:16.614 Trailer[1947]: Performance: Please update this scripting addition to supply a value for ThreadSafe for each event handler: "/Library/ScriptingAdditions/SIMBL.osax"
10/23/15 16:05:16.623 Trailer[1947]: Bartender: Loaded BartenderHelperNinetySix
```

The `Can't find model for source store` error looks interesting.

**Comment by ptsochantaris** [comment] 2015-10-23 15:48
This is useful info, many thanks for posting this @aik099 - I may create a build 1247 with a tweak to try and prevent this from happening to others. I am still not sure what's causing it, but treating the symptom may just be enough.

Sorry once again for this hiccup!

**Comment by aik099** [comment] 2015-10-23 15:56
You're welcome. At least I can make other Trailer users happier.

**Comment by ptsochantaris** [comment] 2015-10-23 16:15
You certainly did, I found the issue thanks to your report!

The problem is a bit complicated, but cutting a long story (very) short, a migration was broken (my bad), and it only failed in OSs outside El Capitan, so my testing didn't pick it up. I assume you're running Yosemite? Trying to replicate your issue in my Yosemite VM caused the issue immediately.

I have fixed the migration now and am uploading build 1247 where it won't occur.

**Comment by ptsochantaris** [comment] 2015-10-23 16:16
(Note to self: Also remember to test migrations on Yosemite from now on!)

**Comment by aik099** [comment] 2015-10-23 17:25
Yes, I'm running Yosemite. Not planning to upgrade to `El Crapitan` yet.

**Comment by ptsochantaris** [comment] 2015-10-23 17:38
Right - thanks for confirming :+1:

No worries though, the issue is now fixed so you shouldn't see any more issues like these in future updates, and I'll be sure to test them more thoroughly next time.

Many thanks again for helping fix this so it doesn't happen to other users.

Looking forward to fixing your original issue as well!

**Comment by ptsochantaris** [comment] 2015-11-05 19:41
I think I may have found the cause for the contradiction of the "refreshing" indicator showing but no greyed-out menu items. It's a small launch-related bug in the code. I have just put up v1.3.10 which fixes that, amongst other changes: https://github.com/ptsochantaris/trailer/releases/tag/v.1.3.10

This doesn't really tell us WHY your sync is failing yet, but it will give us a better idea of what's going on in the first place, as the "weird" state it was getting into didn't help things.

**Comment by ptsochantaris** [comment] 2016-01-23 12:34
Hi, was just wondering if this issue has improved for you at all?

**Comment by aik099** [comment] 2016-01-23 13:37
No problems so far.

**Comment by ptsochantaris** [comment] 2016-01-23 13:40
Nice :+1: Ok, then I'll close this issue for the time being, but please do feel free to (re)open or file a new one in case you spot anything going wrong.

**Closed by ptsochantaris** 2016-01-23 13:40 UTC
