### ISSUE TITLE
Finer control over all repos

### ISSUE THREAD

**Issue by cmluciano** [ptsochantaris/trailer#189] opened 2015-04-13 23:09 UTC
I would love finer grain of display per repo. For example, I may contribute to a large project with many open PRs at a time, and for this specific repo I might want to only show my PRs.

**Comment by ptsochantaris** [comment] 2015-04-14 10:17
Hi! This sounds interesting, as I've been thinking about overhauling the binary "hide/unhide" of repos and making this more fine-grained - what kinds of options per-repo would you want to see?

Thinking of at least, like you said:
- Show none (replaces "hidden")
- Show only my items
- Show only mine & participated (should this be separate from the previous one I wonder?)
- Show all

Ideally it would be nice if this choice was limited to a radio-box style selection, so the current "hide/unhide" box can be replaced by a multiple-choice menu per-repo.  This would also mean replacing the "hide by default" option for repos to "set this visibility level by default".

Also, this feature becomes far more important if you use the issues menu in the upcoming 1.3 - For instance I'd rather see only my/assigned issues across all repos, while I'd rather see all PRs across my watched repos. This would actually mean two different options, and probably to the right of the repo names:

[.................Repo Name..............] [PR Visibility] [Issue Visibility]
[.................Repo Name..............] [PR Visibility] [Issue Visibility]
[.................Repo Name..............] [PR Visibility] [Issue Visibility]

This may be a trick or two to show without clutter in iOS, but on the Mac it should be quite smooth in terms of UI.

Would welcome your thoughts on this.

**Comment by cmluciano** [comment] 2015-04-15 14:57
👍🏽I think a radio style selection is fine. I work with a few projects with 100s of PRs and I normally want to only see mine on those select repos. Then I want to see all on repos that I am a collaborator on.

**Comment by ptsochantaris** [comment] 2015-04-15 15:01
Cool :+1: This makes a lot of sense. It most probably won't make it into 1.3.0 but I'm really keen to introduce it sooner rather than later, as it's something I want as well :)

Reminder to self: This makes the "hide all PRs section" option redundant, but when migrating should set visibility of all un-hidden repos to "show only mine & participated"

**Comment by ptsochantaris** [comment] 2015-05-25 13:04
Hi @cmluciano, I've been working on this feature and have a debug build with the first iteration of it.

The main visible changes here are in the "repositories" tab of preferences, so I'd suggest you visit that and have a look around first.  Because this involved altering sync logic it will need some serious testing to make sure there aren't any regressions, so have a go and let me know how it works out and what kind of problems you get. I'll be using this build as well for the next few days and playing with the settings.

Hope this makes your life a bit easier!  Please do let me know your thoughts on the changes and what problems you may encounter.

https://www.dropbox.com/s/1yvwncunnk8na8l/Trailer-detailed-repo-settings.zip?dl=0

**Comment by ptsochantaris** [comment] 2015-05-25 17:55
Here's a fresher build with improved appearance and logic related to these new settings:

https://www.dropbox.com/s/vmu64g2ibi4xzyy/Trailer-assign-merge-and-close-handling-policy-2.zip?dl=0

**Comment by cmluciano** [comment] 2015-05-25 19:22
This is excellent! I will try it out this week

**Comment by ptsochantaris** [comment] 2015-05-26 08:41
Whoops, wrong link! https://www.dropbox.com/s/bu9wytkesc70k4j/Trailer-detailed-repo-settings-2.zip?dl=0

**Comment by cmluciano** [comment] 2015-05-27 17:30
This is great! It is the exact amount of control that I wanted! 

My only input is that maybe a pointer to the Display option "Count only currently display..." in the release notes. I noticed that my count went way up after adding some repos back, and had to hunt for this option.

Other then that, I'm 👍. As always I appreciate the work you do on this. It changes the way I interact with github in a powerful way!

**Comment by ptsochantaris** [comment] 2015-05-27 17:42
That's great to hear! I really appreciate your comments, it's great to know Trailer is making your work just a little bit easier.

You're absolutely right on the "count only" option, I once forgot it off (the current default) and was weirded out. I've been thinking of setting it to default ON for new users (when off it will count the total of open requests in your repos)

It made a lot of sense to do this initially when Trailer was a very small app, mostly used in-house in single-repo situations, but it's starting to make less and less sense as it goes on. In fact, it probably makes more sense to invert its display meaning and make it "show total of all open PRs in all synced repos" or something similar and have that default off (meaning that by default it will just count the entries listed, which is what users actually expect, I think)

Thanks for testing, and, if possible, please keep using this build to let me know in case some weirdness occurs. If you do run into anything, I'll try to address it ASAP and get back to you with an update.

**Comment by ptsochantaris** [comment] 2015-05-28 21:18
Here's a small update with some font fixes and the aforementioned "count all open PRs" option renamed (and set to off by default): https://www.dropbox.com/s/2edxhkfnzutofgz/Trailer-detailed-repo-settings-3.zip?dl=0

**Comment by ptsochantaris** [comment] 2015-06-03 22:17
Hi, just wanted to let you know that the latest update (1.3.4) is now live, and includes this feature. Will close this for now but please feel free to reopen or post a new issue in case you encounter any other problem!

**Closed by ptsochantaris** 2015-06-03 22:17 UTC
Labels: in next release, will build
