### ISSUE TITLE
Sometimes pulldown menu is placed too high

### ISSUE THREAD

**Issue by dangitall** [ptsochantaris/trailer#284] opened 2016-07-08 21:59 UTC
This is a pretty minor UI issue.

This is what I want to see when I click on the pulldown menu in Trailer:

<img width="459" alt="screen shot 2016-07-08 at 2 50 07 pm" src="https://cloud.githubusercontent.com/assets/882363/16702610/16ebeaa6-451c-11e6-8d3d-3f0c57cf500f.png">

But sometimes I get this:

<img width="498" alt="cut" src="https://cloud.githubusercontent.com/assets/882363/16702636/38da9c02-451c-11e6-8f47-d70df2fad18f.png">

It seems to happen if I have opened the Trailer preferences at some point. Once it happens it persists until I click on one of the menu items, then the entire menu will be shown immediately again.

**Comment by ptsochantaris** [comment] 2016-08-08 01:21
Hi @dangitall and sorry for the slow reply.

I've seen this happen for a while, because I'm not sure what precisely is causing it I had almost given up :) However, your testing and description on how to reproduce it have renewed my interest in investigating it. I'm going to play around and see if I can improve the situation there. Stay tuned.

**Comment by ptsochantaris** [comment] 2017-05-24 18:44
Hi @dangitall - I finally had some time to look this up and fix it. It was purely my unfamiliarity with macOS APIs, using a popup rather than a pulldown style.

The change will be on the next update, but if you'd like to try it out, here's a build with this change included.

[Trailer.zip](https://github.com/ptsochantaris/trailer/files/1026706/Trailer.zip)

Let me know your thoughts and if this improves usage for you.

**Comment by dangitall** [comment] 2017-05-24 19:33
After some quick testing it looks great so far! Thanks!

**Comment by ptsochantaris** [comment] 2017-06-01 20:59
Hi @dangitall - Version 1.5.8 is now up and has this behaviour as well as other features and improvements. I hope the new menu makes your life a bit easier now that the options are consistently placed! Thanks again for posting this issue. I'll close it for now but the suggestions coming in further ones!

**Closed by ptsochantaris** 2017-06-01 20:59 UTC
