### ISSUE TITLE
Trailer isn't showing any PR's

### ISSUE THREAD

**Issue by martyphee** [ptsochantaris/trailer#426] opened 2021-01-19 11:21 UTC
It just recently stopped working. Version 1.7.4 (1572)
I've reinstalled and deleted the directory `com.housetrip.Trailer` from `~/Library/Applicaiton Support`. Still nothing. 

I've turned some repo's on to show all PR's (in excess of 80) and still doesn't show anything. I'm getting some notification in MacOS but trailer isn't showing anything. I'm using the default settings. I didn't change anything except what to view by repo.

![image](https://user-images.githubusercontent.com/754870/105027997-5c713400-5a48-11eb-94d5-1dc0a8196fac.png)

![image](https://user-images.githubusercontent.com/754870/105028055-71e65e00-5a48-11eb-8cb5-44eb227130cc.png)

**Comment by ptsochantaris** [comment] 2021-01-19 12:04
Hi @martyphee - you may want to nuke Trailer preferences back to defaults as some option seems to be causing you some headache by hiding your PRs. Easiest way is to remove the com.housetrip.Trailer file from Preferences when Trailer is not running. This may need you to enter the auth tokens for your servers again though. To be on the safe side, I'd just nuke all the directories you mentioned as well as the prefs and start from scratch. Let me know how it goes.

**Comment by martyphee** [comment] 2021-01-19 14:16
No love. It's been sitting on this screen for > 30m. No wifi issues. I removed the previous file again and `../Preferences/com.housetrip.Trailer.plist`

![image](https://user-images.githubusercontent.com/754870/105045148-78cc9b00-5a5f-11eb-9293-01232fa68a6d.png)

**Comment by ptsochantaris** [comment] 2021-01-20 13:24
That step should take a few seconds at most. Can you activate the two logging options in the "misc" section of preferences and check out the Console.app output for Trailer? Some API call may be failing, and it would be useful to know which one.

**Comment by jg123** [comment] 2021-01-21 21:24
I don't want to hijack this thread, but I also started getting X's for all my trailer icons two days ago. Closing trailer and reopening, and I lost my trailer icons in my menu bar! Clearing preference and sqlite, I can get the Trailer preferences to appear on first run. Closing preferences, and I lose all UI. Tell me to start a new issue if you think it is unrelated. I have attached logs (and removed all the company info from it
[trailer.log](https://github.com/ptsochantaris/trailer/files/5852253/trailer.log)
.

**Comment by ptsochantaris** [comment] 2021-01-23 22:16
Hi @jg123 - yes, if possible please start a new issue about this, as my first guess would be that it's not related. If you can provide a short video or some shots of the behaviour you are describing it would be super useful for me to get a better idea of what the problem is.

**Comment by ptsochantaris** [comment] 2021-01-23 22:18
@martyphee I've seen a few patches of "red-X" during the past 2-3 days as well, I assume GitHub may be having some API issues. Are you still getting the issue above? If so, a log would be extremely useful for debugging.

**Comment by jg123** [comment] 2021-01-25 19:10
> Hi @jg123 - yes, if possible please start a new issue about this, as my first guess would be that it's not related. If you can provide a short video or some shots of the behaviour you are describing it would be super useful for me to get a better idea of what the problem is.

It started working again today. No idea why.

**Comment by martyphee** [comment] 2021-01-25 19:25
> @martyphee I've seen a few patches of "red-X" during the past 2-3 days as well, I assume GitHub may be having some API issues. Are you still getting the issue above? If so, a log would be extremely useful for debugging.

I"ll give it another try tomorrow.

**Comment by martyphee** [comment] 2021-01-26 13:45
Still not working.

Something weird. When I refresh my repository list I see a subset of the repositories compared to when I click on Refresh from the toolbar.

I turned on logging and don't see any errors.

**Comment by martyphee** [comment] 2021-01-26 14:13
On my [notifcations page in github](https://github.com/notifications) I have eight notifications but trailer is showing me nothing. Trailer is a fresh install including removing the two directories with preferences and data.

**Comment by martyphee** [comment] 2021-01-26 14:58
I'm getting some PR's coming through now but still a lot less than shows on my notifications page.

**Comment by annarankin** [comment] 2021-03-17 15:05
Hi there, I think I'm having a similar issue -- I followed the steps above and removed `com.housetrip.Trailer`, re-entered my GH token, and wound up with the long-lived spinner. I exited Trailer and restarted, and immediately got this notification (but no items visible in the drop-down):

![image](https://user-images.githubusercontent.com/11503403/111488654-d30c7400-870f-11eb-9d3c-796b166fbdb3.png)

I feel like this has to be user error on my part somehow 🤔  I do see a PR show up in the dropdown after someone else reviews/comments/approves it, so that's interesting. BTW thank you so much for all your hard work on Trailer, I've loved using it for years! If there's any additional data I can provide that would be helpful, do let me know. Thanks!

**Comment by ptsochantaris** [comment] 2021-05-16 23:39
Hi, just a note on the above discussion, deleting the Trailer database won't really reset your app preferences, as they are saved to macOS, and not the app database. If you want to completely reset Trailer's settings, quit Trailer, then delete Trailer's defaults in `~/Library/Group Containers/group.Trailer`. That should hopefully reset your settings when you start it again.

**Comment by lucascurti** [comment] 2021-08-23 14:26
Try with "Reload All Data". Worked for me.

![image](https://user-images.githubusercontent.com/2811287/130464510-2574012e-4a5d-406a-9624-7be629736d46.png)

**Comment by DiskImage** [comment] 2022-07-13 20:02
I tried all of these, nothing worked, I'm just uninstalling the app—no reinstall—because my previous trust of it is interfering with me actually getting to my team's reviews. I loved it when it worked, but when it stopped it took my awareness of what my team was doing with it because it had completely replaced old habits of watching GH. I do plan to watch this issue for resolution, though, and might try again once this bug is quashed.

Some sort of mechanism in-app to forcibly reset all settings to default (a button really) may have been useful, as would some mechanism to see what was filtered out, and which setting was the reason it was filtered out would go a really long way to helping resolve this stuff. I know that would be a very large lift, based on skimming other issues.

**Closed** 2022-11-10 10:10 UTC
Labels: awaiting feedback
