### ISSUE TITLE
Changing OS X Global shortcut won't persist

### ISSUE THREAD

**Issue by mauricerkelly** [ptsochantaris/trailer#226] opened 2015-10-21 08:23 UTC
I’ve been trying to set up an alternative global shortcut for Trailer on OS X, but I can’t seem to get it to save the alternative. No matter what I change the shortcut to, closing Trailer preferences and re-opening displays the original shortcut configuration again. Is there something I’m missing in the process of setting the shortcut?

**Comment by ptsochantaris** [comment] 2015-10-21 10:37
Hi @mauricerkelly - thanks for reporting this.

Sounds like a bug or perhaps an El-Capitain related regression that needs to be looked at ASAP.

Will look into this and get back to you soon!

**Comment by mauricerkelly** [comment] 2015-10-21 10:38
Can confirm that I'm running on El Capitan. :+1:

**Comment by ptsochantaris** [comment] 2015-10-22 14:42
Definitely confirmed as an issue - will fix ASAP.

**Comment by mauricerkelly** [comment] 2015-10-22 14:44
I'll keep an eye, and try it building from source when it's in :-)

**Comment by ptsochantaris** [comment] 2015-10-22 15:35
Ok, wow, the controls had become unwired from IB for some reason, no idea how I managed it :( I've wired them back up now.

Feel free to build from source and expect a small point update over the weekend with this and hopefully another small feature.

Thanks a lot of spotting this!

Let's leave this open until the next small update so that anyone else having the issue knows there's a fix incoming.

**Comment by ptsochantaris** [comment] 2015-10-22 22:27
Hi! Here's a link to an ongoing test build which should correct this issue: https://www.dropbox.com/s/777yhlnlco6qphi/Trailer-1.3.9-test-1.zip?dl=0

**Comment by ptsochantaris** [comment] 2015-10-22 23:09
And another one, with a fix :) https://www.dropbox.com/s/goqmpmtau4w8p2d/Trailer-1.3.9-test-2.zip?dl=0

**Comment by ptsochantaris** [comment] 2015-10-23 00:12
Actually, this just went out as a release: https://github.com/ptsochantaris/trailer/releases

**Comment by mauricerkelly** [comment] 2015-10-23 10:53
I get this a lot:
![screenshot of trailer 23-10-2015 11 52 56](https://cloud.githubusercontent.com/assets/729402/10690852/9acdc8f6-797c-11e5-9a99-d853ce38e205.png)

**Comment by mauricerkelly** [comment] 2015-10-23 10:58
I direct installed the update and am able to re-assign the global shortcut - yay! Happy to see this closed, but will leave it for you to manage in case you have a process to follow :+1:

**Comment by ptsochantaris** [comment] 2015-10-23 11:02
Yeah, it's a bad one, but thanks for reporting the update issue anyway - If you're running a build earlier than 1.3.9 on El Capitan the updater has broken due to the new security model :( You'll have to upgrade manually from the above link I'm afraid.

I have opened an issue for this to *hopefully* let other people know: https://github.com/ptsochantaris/trailer/issues/227 ...but I'm worried 1.3.7 may become an "albatross" version anyway, as I spotted this issue only yesterday and lots of people may have installed 1.3.7 in El Capitain in the meantime :( I have added notices to the repo and the main site, and will add a notice on the upcoming iOS update release notes, but that's still not going to have a big effect I think. Perhaps in the long run.

Still, glad to hear your issue is fixed! No idea how the code broke there, perhaps I dabbled into too much beta Xcode versions in the summer, but good to have it fixed :)

Thanks again for reporting it!  I'll close this issue in a little while.

**Comment by mauricerkelly** [comment] 2015-10-23 11:06
no problem. I've put in a brew cask update for 1.3.9 so hopefully people can re-install quickly when it gets merged. I'll also pass word around to people in work here to update manually :-)

**Comment by ptsochantaris** [comment] 2015-10-23 11:10
That is awesome, thanks a lot @mauricerkelly - I really appreciate it!

BTW do you have a link/instructions for the brew installation of Trailer? It would be nice to add as an installation option to the README and the site, as many devs may prefer it.

**Comment by mauricerkelly** [comment] 2015-10-23 11:14
If they have brew cask installed already, it really is as simple as:

```shell
brew cask install trailer
```

Getting brew cask installed is the hard bit, though they have the instructions for that over on http://github.com/caskroom/homebrew-cask

**Comment by ptsochantaris** [comment] 2015-10-23 11:16
Well, definitely worth mentioning, thanks! :+1:

**Comment by mauricerkelly** [comment] 2015-10-23 11:23
The updated cask is now available too.

**Comment by ptsochantaris** [comment] 2015-10-23 11:35
Nice! Well, that's one set of users who will get unstuck :+1: 

Thanks again @mauricerkelly!

**Comment by ptsochantaris** [comment] 2015-10-23 16:34
Hm, that version had an ugly bug for Yosemite - it's been fixed now in build 1247 - not sure if this affects your package for cask though. Apologies if it does. I have created a new release record in GitHub, although if your record just points to the trailer139.zip file, then that's fine - it hasn't changed.

**Comment by mauricerkelly** [comment] 2015-10-27 11:30
@ptsochantaris sorry, was away all weekend. It does point to the filename, but also uses a checksum, so I'll get the cask updated!

**Comment by mauricerkelly** [comment] 2015-10-27 11:38
The cask folks were quick to merge today - that’s it fixed now!

**Comment by ptsochantaris** [comment] 2015-10-27 12:38
Nice - thanks once again @mauricerkelly 

The new build seems to be nice and stable for now, fingers crossed :)

It was a very stressful Friday with the updater issue and then rushing a build out that broke on Yosemite :(Sorry for the back and forth on all that. I've got the "include cask as installation source" item on my TODO list, will be adding this soon to the site & repo README :+1: )

**Comment by ptsochantaris** [comment] 2015-11-10 14:53
Closing this issue for now - since I think the issue has been fixed for good :+1: Thanks again for reporting this, as well as all your additional help @mauricerkelly !

**Closed by ptsochantaris** 2015-11-10 14:53 UTC
Labels: bug, Fixed
