### ISSUE TITLE
"Count only currently displayed items in the menu bar" option is ignored for issues

### ISSUE THREAD

**Issue by alexbarton** [ptsochantaris/trailer#202] opened 2015-05-12 23:23 UTC
The counter of the issue menu bar item always displays the number of issues shown in the menu, even when the "count only currently displayed items in the menu bar" option is disabled in the preferences ("display" section).

This option seems to only affect the PR menu bar item.

**Comment by ptsochantaris** [comment] 2015-05-13 07:58
Whoops, you're absolutely right, thanks for reporting this, will be fixed ASAP.

**Comment by ptsochantaris** [comment] 2015-05-13 08:31
As I suspected, it was a pretty simple fix, I hadn't spotted it because I usually keep that setting turned on :) The fix will be in the next release, but here's a corrected version of the existing one in case this is causing you a headache in the meantime:

https://www.dropbox.com/s/4tybjrb7pakbi7t/Trailer-issues-count.zip?dl=0

Thanks again for reporting it!

**Comment by alexbarton** [comment] 2015-05-13 17:36
**Thanks a lot** for this super-fast response and resolution. Works for me!

**Comment by ptsochantaris** [comment] 2015-05-13 18:44
That's great to know!

You're very welcome, it was an oversight while I was adding issue support, so it was very quick and simple to fix :+1: I'll keep this issue open until the next release is live in case someone also encounters this and needs the version with the fix above.

**Comment by ptsochantaris** [comment] 2015-05-21 08:34
Hi, build 1.3.3 is up now and includes this correction. Thanks again for reporting it, and please feel free to reopen or create another issue if you spot any problem or regression!

**Closed by ptsochantaris** 2015-05-21 08:34 UTC
Labels: bug, Fixed, in next release
