### ISSUE TITLE
Trailer dropdown is detached and lower on screen when on desktop with maximized window

### ISSUE THREAD

**Issue by cgatesman** [ptsochantaris/trailer#232] opened 2015-12-23 20:02 UTC
If you have an application maximized in OS X (El Capitan), and drop down Trailer, it appears much lower on the screen instead of up by the Trailer icon.

![screen_shot_2015-12-23_at_2_53_38_pm__2_](https://cloud.githubusercontent.com/assets/6276072/11984063/3a33b976-a986-11e5-9e40-2ca13e468992.png)

**Comment by ptsochantaris** [comment] 2015-12-28 15:10
Hi and thanks for reporting this! Sorry for the late reply, I'm 'away' from my work-related setup because of the vacation period.

I'm going to look into it ASAP but in the meantime I wanted to ask - by 'maximised' are you referring to a window being zoomed to the edges of the screen, or the window being in full-screen mode? Can you perhaps give me an idea of how I could reproduce this using something like e.g. TextEdit?

**Comment by cgatesman** [comment] 2016-01-04 14:04
Sorry for not getting back sooner.  I was out on holiday vacation.  I did a little more investigating on this.  It appears that this only happens on a secondary display.  If I have an application in full screen mode on the secondary display and try to drop down Trailer from that display (through the hidden menu bar at the top), it will behave in this way.

I don't know if this matters, but my main display is a Retina display on a MBP, and my secondary display is an Apple Thunderbolt Display.

**Comment by ptsochantaris** [comment] 2016-01-04 17:28
Hi! Thanks for the update, this is useful info :+1:

So, your setup sounds very similar to what I'm using, and using the steps above I can see that there is some weird behaviour occurring if I try to open the Trailer menu from the secondary display with the "full screen"-ed app.

In my case the effect is even weirder, the menu just shows up on the primary display :) Clearly something is going on there, will look into this ASAP.

**Comment by cgatesman** [comment] 2016-01-04 17:29
Great!  Glad you were able to reproduce it.  I was worried it was something only specific to my setup, and you wouldn't see the problem. :+1:

**Comment by ptsochantaris** [comment] 2016-01-23 13:25
Hi, I think I may have found the issue - here's an intermediate build with (hopefully) this correction. Can you give it a shot when you have some time and see if it helps at all? Thanks!

https://www.dropbox.com/s/4axilguzcbpds17/Trailer-menu-placement.zip?dl=0

**Comment by cgatesman** [comment] 2016-01-25 13:50
Excellent!  Just verified that build fixed the issue I was seeing. :+1:

**Comment by ptsochantaris** [comment] 2016-01-26 10:02
Great news! I wish j could have a good excuse but it was just bad code on my end :( 

Many thanks for reporting and testing it out! I'll push a small update out with this fix soon. 

Meanwhile feel free to use this build, it's a proper release build and should work fine without any issue.

**Comment by ptsochantaris** [comment] 2016-01-28 12:47
Version 1.3.12 is up, and is essentially the same build as the one you have above - but if it makes you feel more secure feel free to re-download it just in case (the auto-updater will probably not prompt you because the public build has the same build number) Link: https://github.com/ptsochantaris/trailer/releases/download/v1.3.12/trailer1312.zip

I'll close this issue for now, but please feel free to open more issues if you spot any other rendering glitches or any other problems!

**Closed by ptsochantaris** 2016-01-28 12:47 UTC
Labels: awaiting feedback, bug, in next release
